export const menuItems = [
  { name: "Home", href: "#home" },
  { name: "About", href: "#about" },
  { name: "Services", href: "#services" },
  { name: "Portfolio", href: "#portfolio" },
  { name: "Testimonials", href: "#testimonials" },
  { name: "Blog", href: "/#blog" },
];
export const menuItemsFooter = [
  { name: "Home", link: "/", page: "home" },
  { name: "About Us", link: "/about", page: "about" },
  { name: "Worker Category", link: "/category", page: "home" },
  { name: "Privacy Policy", link: "/privacy", page: "privacy" },
  { name: "Terms & Conditions", link: "/terms", page: "terms" },
    { name: "Services", link: "/service", page: "home" },
  { name: "Refund Policy", link: "/refund", page: "refund" },
];
export const WorkerCategoryData = [
  {
    slug: "industrial-workers",
    image: "/images/workers/industrial.png",
    title: "Industrial Workers",
    text: "Hire helpers, machine operators, welders, fitters, fabricators, and other skilled industrial workers for factory and manufacturing needs.",
  },
  {
    slug: "construction-workers",
    image: "/images/workers/construction.png",
    title: "Construction Workers",
    text: "Find masons, carpenters, steel fixers, plumbers, electricians, painters, and civil helpers for all types of construction work.",
  },
  {
    slug: "logistics-warehouse-workers",
    image: "/images/workers/logistics.png",
    title: "Logistics & Warehouse Workers",
    text: "Hire loaders, packers, pickers, delivery staff, dispatch workers, and warehouse helpers for logistics and supply chain operations.",
  },
  {
    slug: "agriculture-farm-workers",
    image: "/images/workers/farm.png",
    title: "Agriculture & Farm Workers",
    text: "Get farm labour, tractor drivers, dairy workers, irrigation staff, and crop-cutting workers for agricultural and rural operations.",
  },
  {
    slug: "household-domestic-workers",
    image: "/images/workers/domestic.png",
    title: "Household / Domestic Workers",
    text: "Hire maids, cooks, cleaners, babysitters, patient care staff, and other trusted domestic workers for household support.",
  },
  {
    slug: "automobile-workshop-workers",
    image: "/images/workers/automobile.png",
    title: "Automobile & Workshop Workers",
    text: "Find mechanics, denters, painters, tyre technicians, battery technicians, and workshop helpers for automobile service needs.",
  },
  {
    slug: "retail-service-workers",
    image: "/images/workers/retail.png",
    title: "Retail & Service Workers",
    text: "Hire sales staff, cashiers, store helpers, delivery executives, billing assistants, and retail support workers for shops and outlets.",
  },
  {
    slug: "hospitality-workers",
    image: "/images/workers/hospitality.png",
    title: "Hospitality Workers",
    text: "Get waiters, kitchen staff, housekeeping staff, banquet helpers, catering workers, and hotel support workers for hospitality services.",
  },
  {
    slug: "healthcare-support-workers",
    image: "/images/workers/healthcare.png",
    title: "Healthcare Support Workers",
    text: "Hire ward boys, nursing helpers, patient care staff, hospital cleaners, OT helpers, and medical attendants for healthcare support roles.",
  },
  {
    slug: "security-facility-workers",
    image: "/images/workers/security.png",
    title: "Security & Facility Workers",
    text: "Find security guards, office boys, cleaners, gatekeepers, watchmen, pantry boys, and facility support workers for daily operations.",
  },
  {
    slug: "driving-transport-workers",
    image: "/images/workers/drivers.png",
    title: "Driving & Transport Workers",
    text: "Hire LMV and HMV drivers, auto drivers, tempo drivers, delivery drivers, and transport helpers for mobility and logistics needs.",
  },
];

export const indianStates = {
  'Andhra Pradesh': {
    'Alluri Sitharama Raju': [
      'Addateegala',
      'Ananthagiri',
      'Araku Valley',
      'Chinthapalli',
      'Chinturu',
      'Devipatnam',
      'Dumbriguda',
      'Gangavaram',
      'G.Madugula',
    ],
    Anakapalli: ['Anakapalli', 'Chodavaram', 'Narsipatnam', 'Madugula', 'Kotauratla'],
    Annamaiah: ['Rayachoti', 'Galiveedu', 'Chinnamandem', 'Sambepalli', 'T.Sundupalli'],
    Bapatla: ['Bapatla', 'Chirala', 'Repalle', 'Pittalavanipalem', 'Karlapalem'],
    'Dr. B.R. Ambedkar Konaseema': [
      'Amalapuram',
      'Mummidivaram',
      'Ramachandrapuram',
      'Razole',
      'Kothapeta',
    ],
    Eluru: ['Eluru', 'Jangareddygudem', 'Chintalapudi', 'Polavaram', 'Kukkunoor'],
    Kakinada: ['Kakinada', 'Pithapuram', 'Tuni', 'Prathipadu', 'Samalkot'],
    Nandyal: ['Nandyal', 'Banaganapalle', 'Dhone', 'Atmakur', 'Gospadu'],
    NTR: ['Vijayawada', 'Jaggayyapeta', 'Nandigama', 'Tiruvuru', 'Mylavaram'],
    Palnadu: ['Narasaraopet', 'Macherla', 'Gurazala', 'Pedakurapadu', 'Chilakaluripeta'],
    'Parvathipuram Manyam': ['Parvathipuram', 'Kurupam', 'Saluru', 'Makkuva', 'Gummalakshmipuram'],
    'Sri Potti Sriramulu Nellore': ['Nellore', 'Kavali', 'Gudur', 'Venkatagiri', 'Udayagiri'],
    'Sri Sathya Sai': ['Puttaparthi', 'Dharmavaram', 'Kadiri', 'Penukonda', 'Hindupur'],
    Tirupati: ['Tirupati', 'Srikalahasti', 'Puttur', 'Nagari', 'Chandragiri'],
    Anantapur: ['Dharmavaram', 'Amarapuram', 'Atmakur', 'Palasamudram'],
    Chittoor: [
      'Mulakalacheruvu',
      'Baireddipalle',
      'Bangarupalem',
      'Chittoor',
      'Chowdepalle',
      'Gangadhara Nellore',
      'Gangavaram',
      'Gudipala',
      'Gudupalle',
      'Irala',
      'Karvetinagar',
      'Kuppam',
      'Nagari',
      'Nindra',
      'Palamaner',
      'Palasamudram',
      'Peddapanjani',
      'Penumuru',
      'Pulicherla',
      'Punganur',
      'Puthalapattu',
      'Ramakuppam',
      'Rompicherla',
      'Santhipuram',
      'Sodam',
      'Somala',
    ],
    'East Godavari': ['Rajamahendravaram', 'Kakinada'],
    Guntur: [
      'Pilliptula',
      'Pigugurala',
      'Mettigudipadu Goli I',
      'Mettigudipadu Goli II',
      'Mettigudipadu Goli III',
      'Mettigudipadu Goli IV',
    ],
    Krishna: [
      'Thiruvuru',
      'A. Konduru',
      'Gampalagudem',
      'Vuyyuru',
      'Thotlavalluru',
      'Pamidimukkala',
      'Vissannapeta',
      'Chatrayi',
      'Reddygudem',
    ],
    Kurnool: [
      'Mantralayam',
      'Allagadda',
      'Gospadu',
      'Rudravaram',
      'Sirevella',
      'Chagalamarri',
      'Koilakuntla',
      'Dornipadu',
      'Uyyalawada',
      'Kolimigundla',
      'Sanjamala',
      'Kurnool',
      'Kalluru',
      'Orvakal',
      'Nandyal',
      'Panyam',
      'Gadivemula',
      'Mahanandi',
      'Bandi Atmakur',
    ],
    Nellore: [
      'Seetharamapuram',
      'Allur',
      'Vidavalur',
      'Kodavalur',
      'Buchireddypalem',
      'Sangam',
      'Dagadarthi',
      'Gudur',
      'Manubolu',
      'Sydapuram',
      'Indukurpet',
      'T.P. Gudur',
      'Doravarisatram',
      'Udayagiri',
      'Marripadu',
      'Duttalur',
      'Varikuntapadu',
      'Vinjamu',
      'Kondapuram',
      'Kaligiri',
      'Venkatagiri',
      'Dakkili',
      'Balayapalli',
      'Rapur',
    ],
    Prakasam: [
      'Chimakurthi',
      'Kothapatnam',
      'Maddipadu',
      'Naguluppalapadu',
      'Ongole',
      'Tanguturu',
      'Santhanuthalapadu',
      'Kondapi',
      'Mundlamuru',
      'Singarayakonda',
      'Talluru',
    ],
    Srikakulam: ['Veeraghattam'],
    Visakhapatnam: [
    "Anakapalle",
    "Bheemunipatnam",
    "Chodavaram",
    "Gajuwaka",
    "Pendurthi",
    "Narsipatnam",
    "Visakhapatnam North",
    "Visakhapatnam South"
  ],
  Vizianagaram: [
    "Gajapathinagaram",
    "Jami",
    "Mentada",
    "Parvathipuram",
    "Vizianagaram Rural",
    "Vizianagaram Urban"
  ],
  "West Godavari": [
    "Eluru",
    "Tadepalligudem",
    "Nidadavolu",
    "Palakol",
    "Bhimavaram",
    "Achanta",
    "Devarapalle",
    "Undi"
  ],
    'YSR Kadapa': ['Kondapuram'],
  },
  'Arunachal Pradesh': {
    'Itanagar Capital Complex': ['Itanagar', 'Naharlagun', 'Banderdewa', 'Borum'],
    Kamle: ['Raga', 'Dollungmukh', 'Puchi Geko'],
    'Lepa Rada': ['Basar', 'Daring', 'Sago', 'Tirbin'],
    'Pakke-Kessang': ['Seijosa', 'Pakke-Kessang', 'Pijerang', 'Dissing-Passo'],
    'Shi-Yomi': ['Mechuka', 'Monigong', 'Tato', 'Pidi'],
    'Upper Dibang Valley': ['Anini', 'Etalin', 'Mipi', 'Anelih'],
    Tawang: [
      'Bongkhar',
      'Dudunghar',
      'Jang',
      'Kitpi Circle',
      'Lhou',
      'Lumla',
      'Mukto Circle',
      'Tawang Circle',
      'Thingbu',
      'Zemithang',
    ],
    'West Kameng': [
      'Bomdila',
      'Dirang Circle',
      'Thembang Circle',
      'Nafra Circle',
      'Rupa Circle',
      'Kalaktang Circle',
      'Shergaon Circle',
      'Singchung Circle',
      'Jamiri Circle',
      'Thrizino Circle',
      'Bhalukpong Circle',
      'Kamengbari-Doimara Circle',
    ],
    'East Kameng': ['Chayang-Tajo', 'Bameng', 'Khenewa'],
    'Papum Pare': [
      'Doimukh Circle',
      'Balijan Circle',
      'Borum',
      'Sagalee Circle',
      'Banderdewa',
      'Naharlagun Circle',
      'Kimin Circle',
      'Mengio Circle',
    ],
    'Kurung Kumey': [
      'Sarli',
      'Damin Circle',
      'Parsi-Parlo',
      'Nyapin Circle',
      'Sangram',
      'Koloriang Circle',
    ],
    'Kra Daadi': ['Pipsorang Circle'],
    'Lower Subansiri': [
      'Yachuli Circle',
      'Ziro Circle',
      'Ziro-II',
      'Hong-Hari',
      'Ziro-I',
      'Pistana Circle',
    ],
    'Upper Subansiri': [
      'Daporijo Circle',
      'Siyum Circle',
      'Chetam (Peer Yapu)',
      'Nacho Circle',
      'Giba Circle',
      'Payeng Circle',
      'Dumporijo Circle',
      'Baririjo Circle',
      'Limeking Circle',
      'Taliha Circle',
    ],
    'West Siang': [
      'Bagra Circle',
      'Liromoba Circle',
      'Kamba Circle',
      'Along West',
      'Darak Circle',
      'Along East',
      'Along Circle',
    ],
    'East Siang': ['Pasighat', 'Mebo', 'Ruksin', 'Sille-Oyan'],
    Siang: [
      'Rebo-Perging Circle',
      'Riga Circle',
      'Rumgong Circle',
      'Kaying Circle',
      'Boleng Circle',
      'Pangin Circle',
    ],
    'Upper Siang': [
      'Tuting Circle',
      'Geku Circle',
      'Jengging Circle',
      'Mariyang Circle',
      'Yingkiong Circle',
      'Singa Circle',
    ],
    'Lower Siang': ['Gensi', 'Kangku', 'Likabali', 'Ramle Bango'],
    'Lower Dibang Valley': ['Hunli Circle', 'Dambuk Circle', 'Roing Circle'],
    'Dibang Valley': ['Anini', 'Etalin', 'Anelih', 'Mipi'],
    Anjaw: ['Hawai-Walong', 'Hayuliang-Goiliang', 'Chaglagam', 'Manchal'],
    Lohit: ['Wakro Circle', 'Tezu Circle'],
    Namsai: ['Lekang Circle', 'Namsai Circle', 'Chongkham Circle', 'Piyong', 'Lathaw'],
    Changlang: [
      'Changlang',
      'Kharsang',
      'Miao',
      'Nampong',
      'Bordumsa',
      'Manmao',
      'Yatdam',
      'Vijoynagar',
    ],
    Tirap: ['Dadam', 'Khonsa Circle', 'Namsang Circle', 'Borduria', 'Laju Circle'],
    Longding: ['Niausa', 'Kanubari', 'Longding', 'Pongchau', 'Wakka'],
  },
  Assam: {
    Bajali: ['Pathsala', 'Bhawanipur', 'Patacharkuchi', 'Barpeta Road'],
    Tamulpur: ['Tamulpur', 'Nagrijuli', 'Goreswar', 'Kumarikata'],
    Hojai: ['Hojai', 'Lumding', 'Doboka'],
    Biswanath: ['Biswanath Chariali', 'Gohpur', 'Helem', 'Borgang'],
    Baksa: ['Mushalpur', 'Salbari', 'Tamulpur'],
    Barpeta: ['Barpeta', 'Kalgachia', 'Sarukhetri', 'Sorbhog'],
    // Biswanath: ['Biswanath Chariali', 'Gohpur'],
    Bongaigaon: ['Bongaigaon', 'Abhayapuri'],
    Cachar: ['Silchar', 'Lakhipur'],
    Charaideo: ['Sonari'],
    Chirang: ['Kajalgaon', 'Bijni'],
    Darrang: ['Mangaldoi'],
    Dhemaji: ['Dhemaji', 'Jonai'],
    Dhubri: ['Dhubri', 'Bilasipara'],
    Dibrugarh: ['Dibrugarh', 'Moran', 'Naharkatiya'],
    'Dima Hasao': ['Haflong', 'Diyungbra', 'Maibong'],
    Goalpara: ['Goalpara', 'Lakhipur'],
    Golaghat: ['Golaghat', 'Bokakhat', 'Dhansiri', 'Merapani'],
    Hailakandi: ['Hailakandi', 'Katlicherra'],
    // Hojai: ['Hojai', 'Lumding'],
    Jorhat: ['Jorhat', 'Titabor'],
    Kamrup: ['Kamrup', 'Rangiya'],
    'Kamrup Metropolitan': ['Guwahati', 'Chandrapur', 'Dispur', 'Sonapur', 'Azara'],
    'Karbi Anglong': ['Diphu', 'Bokajan', 'Howraghat'],
    'West Karbi Anglong': ['Hamren'],
    Karimganj: ['Karimganj', 'Ramkrishna Nagar'],
    Kokrajhar: ['Parbatjhora', 'Gossaigaon', 'Kokrajhar'],
    Lakhimpur: ['North Lakhimpur', 'Bihpuria', 'Narayanpur', 'Dhakuakhana'],
    Majuli: ['Garamur'],
    Morigaon: ['Morigaon'],
    Nagaon: ['Nagaon', 'Hathihati', 'Raha', 'Barhampur'],
    Nalbari: ['Nalbari', 'Belsor', 'Choudhury'],
    // 'Dima Hasao': ['Haflong', 'Diyungbra', 'Maibong'],
    Sivasagar: ['Sivasagar', 'Amguri', 'Nalitani'],
    Sonitpur: ['Tezpur', 'Bhalukmari', 'Dhekiajuli'],
    'South Salmara-Mankachar': ['Mankachar', 'Salmara'],
    Tinsukia: ['Tinsukia', 'Margherita'],
    Udalguri: ['Udalguri', 'Dimakuchi'],
    // 'West Karbi Anglong': ['Hamren'],
  },
  Bihar: {
    Sheohar: ['Dumri Katsari', 'Piprarhi', 'Purnahiya', 'Sheohar', 'Tariani Chowk'],
    Gopalganj: [
      'Thawe',
      'Hathua',
      'Kateya',
      'Bhorey',
      'Manjha',
      'Barauli',
      'Gopalganj',
      'Vijayipur',
      'Phulwariya',
      'Uchkagaon',
      'Sidhwaliya',
      'Panchdewari',
      'Kuchaikote',
      'Baikunthpur',
    ],
    'West Champaran': [
      'Bagaha',
      'Bettiah',
      'Chanpatia',
      'Gaunaha',
      'Lauriya',
      'Mainatand',
      'Narkatiaganj',
      'Ramnagar',
      'Sikta',
    ],
    Vaishali: [
      'Hajipur',
      'Mahua',
      'Patepur',
      'Raja Pakar',
      'Bhagwanpur',
      'Bidupur',
      'Lalganj',
      'Desari',
    ],
    Araria: ['Araria', 'Falka', 'Phulparas'],
    Arwal: ['Arwal', 'Kaler', 'Jehanabad'],
    Aurangabad: ['Aurangabad', 'Obra', 'Rafiganj'],
    Banka: ['Banka', 'Amarpur', 'Shambhuganj'],
    Begusarai: ['Begusarai', 'Chhatra', 'Bakhri', 'Teghra'],
    Bhagalpur: ['Bhagalpur', 'Nathnagar', 'Sabour'],
    Bhojpur: ['Arrah', 'Jagdishpur', 'Koilwar'],
    Buxar: ['Buxar', 'Chausa', 'Sikandarpur'],
    Darbhanga: ['Darbhanga', 'Biraul', 'Baheri', 'Benipur'],
    'East Champaran (Motihari)': ['Motihari', 'Chhata', 'Turkaulia', 'Raxaul'],
    Gaya: ['Gaya', 'Bodh Gaya', 'Dumaria'],
    // Gopalganj: ['Gopalganj', 'Banjaria', 'Maharajganj'],
    Jamui: ['Jamui', 'Chakai', 'Jhajha'],
    Jehanabad: ['Jehanabad', 'Makhdumpur', 'Modanganj'],
    'Kaimur (Bhabua)': ['Bhabua', 'Kaimur', 'Ramgarh'],
    Katihar: ['Katihar', 'Balrampur', 'Manihari'],
    Khagaria: ['Khagaria', 'Beldaur', 'Mansi'],
    Kishanganj: ['Kishanganj', 'Chaturbari', 'Bahadurganj'],
    Lakhisarai: ['Lakhisarai', 'Sherpur', 'Barhiya'],
    Madhepura: ['Madhepura', 'Alamnagar', 'Brahmpura'],
    Madhubani: ['Madhubani', 'Benipatti', 'Jaynagar'],
    'Munger (Monghyr)': ['Munger', 'Kharagpur', 'Jamalpur'],
    Muzaffarpur: ['Muzaffarpur', 'Madhupur', 'Paroo'],
    Nalanda: ['Nalanda', 'Hilsa', 'Rajgir'],
    Nawada: ['Nawada', 'Hisua', 'Warishalganj'],
    Patna: ['Patna', 'Bakhtiyarpur', 'Phulwari Sharif'],
    'Purnia (Purnea)': ['Purnia', 'Kasba', 'Raghunathganj'],
    Rohtas: ['Rohtas', 'Sasaram', 'Dehri'],
    Saharsa: ['Saharsa', 'Simri Bakhtiyarpur', 'Mahishi'],
    Samastipur: ['Samastipur', 'Dalsingh Sarai', 'Pusa'],
    Saran: ['Chapra', 'Saran', 'Mashrakh'],
    Sheikhpura: ['Sheikhpura', 'Chewara'],
    // Sheohar: ['Sheohar', 'Paharpur'],
    Sitamarhi: ['Sitamarhi', 'Pipra', 'Bathnaha'],
    Siwan: ['Siwan', 'Raghunathpur', 'Gorakhpur'],
    Supaul: ['Supaul', 'Tribeniganj', 'Nirmali'],
    // Vaishali: ['Hajipur', 'Maharajganj', 'Lalganj'],
    // 'West Champaran': ['Bagaha', 'Chhitauni', 'Lauriya'],
  },
  'Chandigarh (UT)': {
    Chandigarh: [
      'Sector 1',
      'Sector 2',
      'Sector 3',
      'Sector 4',
      'Sector 5',
      'Sector 6',
      'Sector 7',
      'Sector 8',
      'Sector 9',
      'Sector 10',
      'Sector 11',
      'Sector 12',
      'Sector 13',
      'Sector 14',
      'Sector 15',
      'Sector 16',
      'Sector 17',
      'Sector 18',
      'Sector 19',
      'Sector 20',
      'Sector 21',
      'Sector 22',
      'Sector 23',
      'Sector 24',
      'Sector 25',
      'Sector 26',
      'Sector 27',
      'Sector 28',
      'Sector 29',
      'Sector 30',
      'Sector 31',
      'Sector 32',
      'Sector 33',
      'Sector 34',
      'Sector 35',
      'Sector 36',
      'Sector 37',
      'Sector 38',
      'Sector 39',
      'Sector 40',
      'Sector 41',
      'Sector 42',
      'Sector 43',
      'Sector 44',
      'Sector 45',
      'Sector 46',
      'Sector 47',
      'Sector 48',
      'Sector 49',
      'Sector 50',
      'Sector 51',
      'Sector 52',
      'Sector 53',
      'Sector 54',
      'Sector 55',
      'Sector 56',
      'Sector 57',
      'Sector 58',
      'Sector 59',
      'Sector 60',
    ],
  },
  Chhattisgarh: {
    'Gaurela-Pendra-Marwahi': ['Gaurela', 'Pendra', 'Marwahi'],
    'Khairagarh-Chhuikhadan-Gandai': ['Khairagarh', 'Chhuikhadan', 'Gandai'],
    'Manendragarh-Chirmiri-Bharatpur': ['Manendragarh', 'Chirmiri', 'Bharatpur'],
    'Mohla-Manpur-Chowki': ['Mohla', 'Manpur', 'Chowki'],
    'Sarangarh-Bilaigarh': ['Sarangarh', 'Bilaigarh', 'Kasdol'],
    Sakti: ['Sakti', 'Jaijaipur', 'Dabhra'],
    Balod: ['Balod', 'Dondi', 'Gundardehi', 'Kunernar', 'Pohra', 'Rajpur'],
    'Baloda Bazar': ['Baloda Bazar', 'Bhatapara', 'Kasdol', 'Nawagarh', 'Pendra', 'Tilda'],
    Balrampur: ['Balrampur', 'Kusmi', 'Lailunga', 'Pendra', 'Ramanujganj'],
    Bastar: ['Bastar', 'Jagdalpur', 'Dantewada', 'Kondagaon', 'Keshkal', 'Bailadila'],
    Bemetara: ['Bemetara', 'Nandgaon', 'Sankra', 'Patharia', 'Mungeli'],
    Bijapur: ['Bijapur', 'Bhopalpattanam', 'Basaguda', 'Kutru', 'Peddagelur'],
    Bilaspur: ['Bilaspur', 'Takhatpur', 'Masturi', 'Pendra', 'Katghora', 'Ratanpur'],
    'Dantewada (South Bastar)': ['Dantewada', 'Geedam', 'Bacheli', 'Konta', 'Chhindgarh'],
    Dhamtari: ['Dhamtari', 'Kurud', 'Magarlod', 'Ramnagar', 'Sihawa'],
    Durg: ['Durg', 'Bhilai', 'Patan', 'Jamul', 'Bhansi', 'Khallari'],
    Gariyaband: ['Gariyaband', 'Bindranavagarh', 'Chhura', 'Malkangiri'],
    'Janjgir-Champa': ['Janjgir', 'Champa', 'Kusmunda', 'Naila', 'Dabhra'],
    Jashpur: ['Jashpur', 'Kunkuri', 'Bagicha', 'Patthalgaon', 'Duldula'],
    'Kabirdham (Kawardha)': ['Kawardha', 'Pandariya', 'Chhurra', 'Bodla'],
    'Kanker (North Bastar)': ['Kanker', 'Charama', 'Kanker', 'Dondengaon', 'Bhanupratappur'],
    Kondagaon: ['Kondagaon', 'Dundera', 'Pakhanjore', 'Mungeli'],
    Korba: ['Korba', 'Katghora', 'Pali', 'Farishtabad', 'Kudargari'],
    'Korea (Koriya)': ['Koriya', 'Bharatpur', 'Baikunthpur', 'Khairagarh', 'Manendragarh'],
    Mahasamund: ['Mahasamund', 'Bagbahra', 'Saraipali', 'Pithora', 'Basna'],
    Mungeli: ['Mungeli', 'Lormi', 'Pendra', 'Takhatpur', 'Bilaspur'],
    Narayanpur: ['Narayanpur', 'Orchha', 'Kumarwahi', 'Dhanora'],
    Raigarh: ['Raigarh', 'Kharsia', 'Dharamjaigarh', 'Gharghoda', 'Kirodimal'],
    Raipur: ['Raipur', 'Arang', 'Abhanpur', 'Tilda', 'Kurud'],
    Rajnandgaon: ['Rajnandgaon', 'Dongargaon', 'Khairagarh', 'Chhura', 'Dhamtari'],
    Sukma: ['Sukma', 'Bhadrachalam', 'Chintalnar', 'Burkapal', 'Konta'],
    Surajpur: ['Surajpur', 'Pratappur', 'Bhatgaon', 'Lakhanpur'],
    Surguja: ['Ambikapur', 'Udaipur', 'Bishrampur', 'Mainpat', 'Sitapur'],
  },
  'Dadra and Nagar Haveli (UT)': {
    'Dadra & Nagar Haveli': ['Dadra', 'Silvassa', 'Vasona', 'Khadiya', 'Dapada', 'Khanvel'],
  },
  'Daman and Diu (UT)': {
    Daman: ['Daman', 'Nani Daman', 'Moti Daman', 'Daman Ganga', 'Kochi'],
    Diu: ['Diu', 'Fudam', 'Sankar', 'Nani Diu', 'Moti Diu'],
  },
  'Delhi (NCT)': {
    'Central Delhi': [
      'Daryaganj',
      'Kashmere Gate',
      'Kamla Nagar',
      'Paharganj',
      'Connaught Place',
      'Chandni Chowk',
    ],
    'East Delhi': [
      'Preet Vihar',
      'Laxmi Nagar',
      'Mayur Vihar',
      'Karkardooma',
      'Anand Vihar',
      'Shahdara',
    ],
    'New Delhi': ['Connaught Place', 'Chanakyapuri', 'Raisina', 'Moti Bagh', 'Lodhi Colony'],
    'North Delhi': ['Civil Lines', 'Sadar Bazar', 'Model Town', 'Shalimar Bagh'],
    'North East Delhi': ['Seelampur', 'Shahdara', 'Ghonda', 'Karawal Nagar'],
    'North West Delhi': ['Pitampura', 'Rohini', 'Shakur Basti', 'Bawana'],
    Shahdara: [
      'Shahdara',
      'Seemapuri',
      'Mansarovar Park',
      'Dilshad Garden',
      'Vivek Vihar',
      'Jhilmil Colony',
      'Welcome Colony',
      'Krishna Nagar',
      'Karkardooma',
      'Anand Vihar',
      'Babarpur',
      'Maujpur',
      'Zafrabad',
      'Ghonda',
      'Yamuna Vihar',
      'Old Seelampur',
      'Tahirpur',
      'Saboli',
      'Mandoli',
      'Gagan Vihar',
      'Jagatpuri',
      'Vishwas Nagar',
      'Anand Nagar',
    ],
    'South Delhi': ['Saket', 'Mehrauli', 'Vasant Kunj', 'Chhattarpur', 'Greater Kailash'],
    'South East Delhi': ['Okhla', 'Sarita Vihar', 'Jamia Nagar', 'Kalkaji'],
    'South West Delhi': ['Dwarka', 'Janakpuri', 'Vikaspuri', 'Najafgarh'],
    'West Delhi': ['Punjabi Bagh', 'Rajouri Garden', 'Subhash Nagar', 'Tilak Nagar', 'Moti Nagar'],
  },
  Goa: {
    'North Goa': ['Mapusa', 'Panaji', 'Bardez', 'Bicholim', 'Pernem', 'Sattari', 'Tiswadi'],
    'South Goa': ['Margao', 'Quepem', 'Sanguem', 'Canacona', 'Salcete'],
  },
  Gujarat: {
    Ahmedabad: [
      'Ahmedabad City',
      'Bavla',
      'Dholka',
      'Sanand',
      'Dhandhuka',
      'Mandal',
      'Detroj-Rampura',
      'Viramgam',
    ],
    Amreli: [
      'Amreli',
      'Lathi',
      'Savar Kundla',
      'Rajula',
      'Khambha',
      'Jafrabad',
      'Bagasara',
      'Dhari',
    ],
    Anand: ['Anand', 'Borsad', 'Khambhat', 'Petlad', 'Sojitra', 'Tarapur', 'Umreth', 'Anklav'],
    Aravalli: ['Modasa', 'Malpur', 'Bhiloda', 'Bayad', 'Meghraj', 'Dhansura'],
    'Banaskantha (Palanpur)': [
      'Palanpur',
      'Deesa',
      'Tharad',
      'Vav',
      'Dhanera',
      'Kankrej',
      'Dantiwada',
      'Vadgam',
    ],
    Bharuch: ['Bharuch', 'Ankleshwar', 'Jambusar', 'Vagra', 'Amod', 'Hansot', 'Jhagadia'],
    Bhavnagar: [
      'Bhavnagar',
      'Gariadhar',
      'Mahuva',
      'Palitana',
      'Sihor',
      'Vallabhipur',
      'Talaja',
      'Ghogha',
    ],
    Botad: ['Botad', 'Barwala', 'Ranpur', 'Gadhada'],
    'Chhota Udepur': ['Chhota Udepur', 'Bodeli', 'Nasvadi', 'Kawant', 'Jetpur-Pavi', 'Sankheda'],
    Dahod: ['Dahod', 'Garbada', 'Devgadh Baria', 'Limkheda', 'Dhanpur', 'Fatepura'],
    'Dangs (Ahwa)': ['Ahwa', 'Waghai', 'Subir'],
    'Devbhoomi Dwarka': ['Khambhalia', 'Dwarka', 'Kalyanpur', 'Bhanvad'],
    Gandhinagar: ['Gandhinagar', 'Kalol', 'Mansa', 'Dehgam'],
    'Gir Somnath': ['Veraval', 'Kodinar', 'Una', 'Talala', 'Sutrapada', 'Gir Gadhada'],
    Jamnagar: ['Jamnagar', 'Khambhalia', 'Jodiya', 'Lalpur', 'Kalavad', 'Jamjodhpur'],
    Junagadh: [
      'Junagadh',
      'Mendarda',
      'Visavadar',
      'Manavadar',
      'Keshod',
      'Mangrol',
      'Bhesan',
      'Vanthali',
    ],
    Kachchh: ['Bhuj', 'Anjar', 'Nakhtrana', 'Mundra', 'Mandvi', 'Rapar', 'Gandhidham', 'Abdasa'],
    'Kheda (Nadiad)': [
      'Nadiad',
      'Kheda',
      'Matar',
      'Mahudha',
      'Kapadvanj',
      'Mehmedabad',
      'Thasra',
      'Galteshwar',
    ],
    Mahisagar: ['Lunawada', 'Kadana', 'Santrampur', 'Virpur', 'Balasinor', 'Khanpur'],
    Mehsana: [
      'Mehsana',
      'Visnagar',
      'Unjha',
      'Vadnagar',
      'Kadi',
      'Becharaji',
      'Satlasana',
      'Vijapur',
    ],
    Morbi: ['Morbi', 'Wankaner', 'Halvad', 'Maliya', 'Tankara'],
    'Narmada (Rajpipla)': ['Rajpipla', 'Dediapada', 'Sagbara', 'Tilakwada'],
    Navsari: ['Navsari', 'Gandevi', 'Chikhli', 'Jalalpore', 'Vansda'],
    'Panchmahal (Godhra)': ['Godhra', 'Halol', 'Kalol', 'Jambughoda', 'Shehera', 'Morwa (Hadaf)'],
    Patan: ['Patan', 'Sidhpur', 'Radhanpur', 'Harij', 'Sami', 'Santalpur', 'Shankheshwar'],
    Porbandar: ['Porbandar', 'Kutiyana', 'Ranavav'],
    Rajkot: [
      'Rajkot',
      'Jasdan',
      'Upleta',
      'Kotda Sangani',
      'Paddhari',
      'Dhoraji',
      'Lodhika',
      'Gondal',
    ],
    'Sabarkantha (Himmatnagar)': [
      'Himmatnagar',
      'Idar',
      'Prantij',
      'Talod',
      'Khedbrahma',
      'Vadali',
      'Poshina',
      'Vijaynagar',
    ],
    Surat: [
      'Surat City',
      'Surat Rural',
      'Olpad',
      'Mahuva',
      'Mandvi',
      'Bardoli',
      'Kamrej',
      'Choryasi',
      'Palsana',
      'Umarpada',
    ],
    Surendranagar: [
      'Surendranagar',
      'Chotila',
      'Wadhwan',
      'Dhrangadhra',
      'Halvad',
      'Limbdi',
      'Lakhtar',
      'Sayla',
      'Muli',
    ],
    'Tapi (Vyara)': ['Vyara', 'Songadh', 'Nizar', 'Uchchhal', 'Dolvan', 'Kukarmunda'],
    Vadodara: ['Vadodara', 'Karjan', 'Savli', 'Padra', 'Dabhoi', 'Waghodia', 'Sinor'],
    Valsad: ['Valsad', 'Vapi', 'Pardi', 'Umbergaon', 'Dharampur', 'Kaprada'],
  },
  Haryana: {
    Ambala: ['Ambala', 'Ambala Cantt', 'Barara', 'Naraingarh', 'Saha', 'Mullana', 'Shahzadpur'],
    Bhiwani: ['Bhiwani', 'Loharu', 'Tosham', 'Siwani', 'Bawani Khera'],
    CharkhiDadri: ['Charkhi Dadri', 'Badhra'],
    Faridabad: ['Faridabad', 'Ballabgarh', 'Tigaon', 'Badkhal'],
    Fatehabad: ['Fatehabad', 'Ratia', 'Tohana', 'Sardulgarh'],
    Gurgaon: ['Gurgaon', 'Manesar', 'Pataudi'],
    Hisar: ['Hisar', 'Narnaund', 'Adampur', 'Hansi', 'Barwala'],
    Jhajjar: ['Jhajjar', 'Bahadurgarh', 'Matanhail', 'Beri'],
    Jind: ['Jind', 'Safidon', 'Uchana', 'Narwana'],
    Kaithal: ['Kaithal', 'Kalka', 'Pundri', 'Guhla'],
    Karnal: ['Karnal', 'Assandh', 'Gharaunda', 'Indri', 'Nilokheri'],
    Kurukshetra: ['Kurukshetra', 'Thanesar', 'Pehowa', 'Shahabad'],
    Mahendragarh: ['Mahendragarh', 'Narnaul', 'Ateli'],
    Mewat: ['Nuh', 'Firozpur Jhirka', 'Punhana', 'Tauru'],
    Palwal: ['Palwal', 'Hodal', 'Ballabgarh'],
    Panchkula: ['Panchkula', 'Pinjore', 'Kalka'],
    Panipat: ['Panipat', 'Samalkha', 'Israna'],
    Rewari: ['Rewari', 'Bawal', 'Kosli'],
    Rohtak: ['Rohtak', 'Sampla', 'Meham', 'Lakhan Majra'],
    Sirsa: ['Sirsa', 'Rania', 'Dabwali', 'Ellenabad'],
    Sonipat: ['Sonipat', 'Ganaur', 'Kharkhoda', 'Gohana'],
    Yamunanagar: ['Yamunanagar', 'Jagadhri', 'Radaur', 'Bilaspur', 'Chhachhrauli'],
  },
  'Himachal Pradesh': {
    Bilaspur: ['Bilaspur', 'Jhandutta', 'Shampur', 'Ghumarwin'],
    Chamba: ['Chamba', 'Bharmaur', 'Dalhousie', 'Churah'],
    Hamirpur: ['Hamirpur', 'Nadaun', 'Bamsan', 'Sujanpur'],
    Kangra: ['Dharamsala', 'Baijnath', 'Nagrota', 'Palampur'],
    Kinnaur: ['Kinnaur', 'Pooh', 'Kalpa'],
    Kullu: ['Kullu', 'Manali', 'Banjar', 'Ani'],
    'Lahaul & Spiti': ['Keylong', 'Uppar Lahaul', 'Spiti'],
    Mandi: ['Mandi', 'Kullu', 'Balh', 'Sundernagar'],
    Shimla: ['Shimla', 'Kullu', 'Chopal', 'Kandaghat'],
    'Sirmaur (Sirmour)': ['Nahan', 'Paonta Sahib', 'Rajban', 'Shillai'],
    Solan: ['Solan', 'Kandaghat', 'Nalagarh', 'Arki'],
    Una: ['Una', 'Amb', 'Haroli', 'Bangana'],
  },
  'Jammu and Kashmir': {
    Anantnag: ['Anantnag', 'Bijbehara', 'Dooru', 'Pahalgam'],
    Bandipore: ['Bandipore', 'Sumbal', 'Hajin', 'Nawabagh'],
    Baramulla: ['Baramulla', 'Sopore', 'Pattan', 'Kreeri'],
    Budgam: ['Budgam', 'Chadura', 'Khansahib', 'Magam'],
    Doda: ['Doda', 'Bhaderwah', 'Kishtwar', 'Bhallessa'],
    Ganderbal: ['Ganderbal', 'Gurez', 'Kangan', 'Wangath'],
    Jammu: ['Jammu', 'Akhnoor', 'RS Pura', 'Bishnah'],
    Kargil: ['Kargil', 'Zanskar', 'Drass'],
    Kathua: ['Kathua', 'Hiranagar', 'Billawar', 'Bani'],
    Kishtwar: ['Kishtwar', 'Doda', 'Chatroo', 'Paddar'],
    Kulgam: ['Kulgam', 'Qazigund', 'Khiram', 'Yaripora'],
    Kupwara: ['Kupwara', 'Handwara', 'Langate', 'Kralpora'],
    Leh: ['Leh', 'Nubra', 'Zanskar'],
    Poonch: ['Poonch', 'Surankote', 'Mendhar', 'Rajouri'],
    Pulwama: ['Pulwama', 'Awantipora', 'Tral', 'Rajpora'],
    Rajouri: ['Rajouri', 'Nowshera', 'Sunderbani', 'Manjakote'],
    Ramban: ['Ramban', 'Banihal', 'Chanderkote', 'Khari'],
    Reasi: ['Reasi', 'Katra', 'Mahore', 'Arnas'],
    Samba: ['Samba', 'Vijaypur', 'Mansar', 'Ramgarh'],
    Shopian: ['Shopian', 'Zainapora', 'Chitragam', 'Beltangoo'],
    Srinagar: ['Srinagar', 'Habba Kadal', 'Rajbagh', 'Shalteng'],
    Udhampur: ['Udhampur', 'Chenani', 'Reasi', 'Ramnagar'],
  },
  Jharkhand: {
    Bokaro: ['Bokaro', 'Chas', 'Phusro', 'Gomia'],
    Chatra: ['Chatra', 'Simariya', 'Kedla', 'Itkhori'],
    Deoghar: ['Deoghar', 'Madhupur', 'Sarasabad', 'Devipur'],
    Dhanbad: ['Dhanbad', 'Jharia', 'Baghmara', 'Tundi'],
    Dumka: ['Dumka', 'Jama', 'Gopikandar', 'Sarsabad'],
    'East Singhbhum': ['Jamshedpur', 'Ghatshila', 'Mango', 'Chandil'],
    Garhwa: ['Garhwa', 'Ranka', 'Kandi', 'Bharno'],
    Giridih: ['Giridih', 'Tundi', 'Pirtand', 'Dhanwar'],
    Godda: ['Godda', 'Mehndiya', 'Poreyahat', 'Sunderpahari'],
    Gumla: ['Gumla', 'Ranchi', 'Basia', 'Dumri'],
    Hazaribag: ['Hazaribag', 'Koderma', 'Chouparan', 'Sadar'],
    Jamtara: ['Jamtara', 'Karma', 'Fatehpur', 'Nala'],
    Khunti: ['Khunti', 'Murhu', 'Rania', 'Arki'],
    Koderma: ['Koderma', 'Jhumra', 'Chandwara', 'Satgawan'],
    Latehar: ['Latehar', 'Balumath', 'Barwadih', 'Manika'],
    Lohardaga: ['Lohardaga', 'Kuru', 'Bhandra', 'Jori'],
    Pakur: ['Pakur', 'Hiranpur', 'Shikaripara', 'Pakur Town'],
    Palamu: ['Palamu', 'Daltonganj', 'Chhatarpur', 'Panki', 'bisharampur'],
    Ramgarh: ['Ramgarh', 'Madhuban', 'Mandu', 'Gola'],
    Ranchi: ['Ranchi', 'Kanke', 'Hatia', 'Ratu'],
    Sahibganj: ['Sahibganj', 'Rajmahal', 'Udhwa', 'Taljhari'],
    'Seraikela-Kharsawan': ['Seraikela', 'Kharsawan', 'Chandil', 'Gamharia'],
    Simdega: ['Simdega', 'Thethaitangar', 'Kolebira', 'Palkot'],
    'West Singhbhum': ['Chaibasa', 'Jagannathpur', 'Manoharpur', 'Noamundi'],
  },
  Karnataka: {
    Bagalkot: ['Bagalkot', 'Badami', 'Hunagund', 'Jamkhandi'],
    'Ballari (Bellary)': ['Ballari', 'Hospet', 'Harpanahalli', 'Sandur'],
    'Belagavi (Belgaum)': ['Belagavi', 'Chikodi', 'Gokak', 'Bailhongal'],
    'Bengaluru (Bangalore) Rural': ['Devanahalli', 'Hoskote', 'Anekal', 'Doddaballapura'],
    'Bengaluru (Bangalore) Urban': ['Bengaluru', 'Yelahanka', 'Bangalore South', 'Bangalore North'],
    Bidar: ['Bidar', 'Basavakalyan', 'Bhalki', 'Aurad'],
    Chamarajanagar: ['Chamarajanagar', 'Kollegal', 'Yelandur', 'Challakere'],
    Chikballapur: ['Chikballapur', 'Gauribidanur', 'Bagepalli', 'Chintamani'],
    'Chikkamagaluru (Chikmagalur)': ['Chikkamagaluru', 'Mudigere', 'Kadur', 'Tarikere'],
    Chitradurga: ['Chitradurga', 'Holalkere', 'Molakalmuru', 'Hosadurga'],
    'Dakshina Kannada': ['Mangalore', 'Puttur', 'Sullia', 'Bantwal'],
    Davangere: ['Davangere', 'Harapanahalli', 'Jagalur', 'Channarayapatna'],
    Dharwad: ['Dharwad', 'Hubli', 'Kalghatgi', 'Navalgund'],
    Gadag: ['Gadag', 'Bagalkot', 'Ron', 'Sirode'],
    Hassan: ['Hassan', 'Arasikere', 'Alur', 'Channarayapatna'],
    Haveri: ['Haveri', 'Ranebennur', 'Savanur', 'Byadgi'],
    'Kalaburagi (Gulbarga)': ['Kalaburagi', 'Afzalpur', 'Aland', 'Chincholi'],
    Kodagu: ['Madikeri', 'Virajpet', 'Somwarpet', 'Ponnampet'],
    Kolar: ['Kolar', 'Bangarapet', 'Malur', 'Srinivaspur'],
    Koppal: ['Koppal', 'Gangavati', 'Yelburga', 'Hanamasagar'],
    Mandya: ['Mandya', 'Maddur', 'Krishna Raja Pet', 'Nagamangala'],
    'Mysuru (Mysore)': ['Mysuru', 'Hunsur', 'Nanjangud', 'T. Narasipura'],
    Raichur: ['Raichur', 'Sindhanur', 'Manvi', 'Lingasugur'],
    Ramanagara: ['Ramanagara', 'Channapatna', 'Magadi', 'Kanakapura'],
    'Shivamogga (Shimoga)': ['Shivamogga', 'Sagar', 'Shikaripura', 'Thirthahalli'],
    'Tumakuru (Tumkur)': ['Tumakuru', 'Tiptur', 'Kunigal', 'Pavagada'],
    Udupi: ['Udupi', 'Kundapura', 'Karkala', 'Hebri'],
    'Uttara Kannada (Karwar)': ['Karwar', 'Uppinangadi', 'Sirsi', 'Honavar'],
    'Vijayapura (Bijapur)': ['Vijayapura', 'Sindagi', 'Bagalkot', 'Bijapur Town'],
    Yadgir: ['Yadgir', 'Shahapur', 'Gulbarga', 'Jevargi'],
  },
  Kerala: {
    Alappuzha: ['Alappuzha', 'Cherthala', 'Kuttanadu', 'Mavelikara'],
    Ernakulam: ['Ernakulam', 'Kochi', 'Aluva', 'Perumbavoor'],
    Idukki: ['Idukki', 'Devikulam', 'Munnar', 'Peerumedu'],
    Kannur: ['Kannur', 'Thalassery', 'Payyannur', 'Iritty'],
    Kasaragod: ['Kasaragod', 'Kanhangad', 'Badiyadukka', 'Vidyagiri'],
    Kollam: ['Kollam', 'Punalur', 'Kottarakara', 'Chavara'],
    Kottayam: ['Kottayam', 'Changanassery', 'Puthuppally', 'Vaikom'],
    Kozhikode: ['Kozhikode', 'Vadakara', 'Koyilandy', 'Quilandy'],
    Malappuram: ['Malappuram', 'Perinthalmanna', 'Mankada', 'Tirur'],
    Palakkad: ['Palakkad', 'Ottappalam', 'Alathur', 'Mannarkkad'],
    Pathanamthitta: ['Pathanamthitta', 'Adoor', 'Konni', 'Ranni'],
    Thiruvananthapuram: ['Thiruvananthapuram', 'Nedumangadu', 'Varkala', 'Parassala'],
    Thrissur: ['Thrissur', 'Irinjalakuda', 'Kunnamkulam', 'Chalakudy'],
    Wayanad: ['Wayanad', 'Kalpetta', 'Sultan Bathery', 'Mananthavady'],
  },
  'Lakshadweep (UT)': {
    Agatti: ['Agatti'],
    Amini: ['Amini'],
    Androth: ['Androth'],
    Bithra: ['Bithra'],
    Chethlath: ['Chethlath'],
    Kavaratti: ['Kavaratti'],
    Kadmath: ['Kadmath'],
    Kalpeni: ['Kalpeni'],
    Kilthan: ['Kilthan'],
    Minicoy: ['Minicoy'],
  },
  'Madhya Pradesh': {
    'Agar Malwa': ['Agar', 'Badod', 'Nalkheda', 'Susner'],
    Alirajpur: ['Alirajpur', 'Bhavra', 'Jobat', 'Katthiwada'],
    Anuppur: ['Anuppur', 'Jaithari', 'Pushprajgarh', 'Kotma'],
    Ashoknagar: ['Ashoknagar', 'Chanderi', 'Isagarh', 'Mungaoli'],
    Balaghat: ['Balaghat', 'Baihar', 'Katangi', 'Kirnapur', 'Lanji', 'Paraswada', 'Waraseoni'],
    Barwani: ['Barwani', 'Anjad', 'Niwali', 'Pansemal', 'Pati', 'Rajpur', 'Sendhwa', 'Thikri'],
    Betul: ['Betul', 'Amla', 'Bhainsdehi', 'Chicholi', 'Ghodadongri', 'Multai', 'Shahpur'],
    Bhind: ['Bhind', 'Ater', 'Gohad', 'Lahar', 'Mehgaon', 'Mihona', 'Roun'],
    Bhopal: ['Berasia', 'Huzur'],
    Burhanpur: ['Burhanpur', 'Khaknar', 'Nepanagar'],
    Chhatarpur: [
      'Chhatarpur',
      'Bada Malhera',
      'Bijawar',
      'Gaurihar',
      'Laundi',
      'Maharajpur',
      'Nowgong',
      'Rajnagar',
    ],
    Chhindwara: [
      'Chhindwara',
      'Amarwara',
      'Bichhua',
      'Harrai',
      'Jamai',
      'Mohkhed',
      'Pandhurna',
      'Parasia',
      'Sausar',
      'Tamia',
      'Umreth',
    ],
    Damoh: ['Damoh', 'Batiyagarh', 'Hatta', 'Jabera', 'Patharia', 'Patera', 'Tendukheda'],
    Datia: ['Datia', 'Bhander', 'Indergarh', 'Seondha'],
    Dewas: ['Dewas', 'Bagli', 'Kannod', 'Khategaon', 'Sonkatch', 'Tonk Khurd', 'Hatpipliya'],
    Dhar: [
      'Dhar',
      'Badnawar',
      'Dharampuri',
      'Gandhwani',
      'Kukshi',
      'Manawar',
      'Sardarpur',
      'Pithampur',
      'Nalchha',
      'Tirla',
    ],
    Ujjain: ['Ujjain', 'Badnagar', 'Tarana', 'Ghatiya', 'Karchha'],
    Dindori: ['Dindori', 'Bajag', 'Mehadwani', 'Shahpura'],
    Guna: ['Guna', 'Aron', 'Bamori', 'Chachoda', 'Raghogarh', 'Ruthiyai'],
    Gwalior: ['Gwalior', 'Bhitarwar', 'Dabra'],
    Harda: ['Harda', 'Khirkiya', 'Timarni'],
    Hoshangabad: ['Hoshangabad', 'Babai', 'Itarsi', 'Pipariya', 'Seoni Malwa', 'Sohagpur'],
    Indore: ['Indore', 'Depalpur', 'Mhow', 'Sanwer'],
    Jabalpur: ['Jabalpur', 'Kundam', 'Majholi', 'Panagar', 'Patan', 'Sihora', 'Shahpura'],
    Jhabua: ['Jhabua', 'Meghnagar', 'Petlawad', 'Ranapur', 'Thandla'],
    Katni: ['Katni', 'Badwara', 'Bahoriband', 'Barhi', 'Dhimarkheda', 'Murwara', 'Vijayraghavgarh'],
    Khandwa: ['Khandwa', 'Harsud', 'Pandhana', 'Punasa'],
    Khargone: ['Khargone', 'Barwaha', 'Bhikangaon', 'Jhirnya', 'Kasrawad', 'Maheshwar', 'Segaon'],
    Mandla: ['Mandla', 'Bichhiya', 'Ghughri', 'Nainpur', 'Niwas'],
    Mandsaur: ['Mandsaur', 'Garoth', 'Malhargarh', 'Sitamau'],
    Morena: ['Morena', 'Ambah', 'Joura', 'Porsa', 'Sabalgarh'],
    Narsinghpur: ['Narsinghpur', 'Gadarwara', 'Gotegaon', 'Kareli', 'Tendukheda'],
    Neemuch: ['Neemuch', 'Jawad', 'Manasa', 'Singoli'],
    Niwari: ['Niwari', 'Orchha', 'Prithvipur'],
    Panna: ['Panna', 'Ajaigarh', 'Gunnor', 'Pawai', 'Shahnagar'],
    Raisen: ['Raisen', 'Bareli', 'Begamganj', 'Gairatganj', 'Silwani', 'Udaipura'],
    Rajgarh: [
      'Rajgarh',
      'Biaora',
      'Khilchipur',
      'Khujner',
      'Narsinghgarh',
      'Pachore',
      'Sarangpur',
      'Zirapur',
    ],
    Ratlam: ['Ratlam', 'Alot', 'Bajna', 'Jaora', 'Piploda', 'Sailana'],
    Rewa: [
      'Rewa',
      'Gurh',
      'Hanumana',
      'Huzur',
      'Mauganj',
      'Raipur Karchuliyan',
      'Sirmaur',
      'Teonthar',
      'Semariya',
    ],
    Sidhi: [
      "Bahari",
      "Churhat",
      "Gopad Banas",
      "Majhauli",
      "Kusmi",
      "Rampur Naikin",
      "Sihawal"
    ],
    Sagar: ['Sagar', 'Banda', 'Bina', 'Deori', 'Garhakota', 'Khurai', 'Rehli', 'Shahgarh'],
    Satna: [
      'Satna',
      'Birsinghpur',
      'Kotar',
      'Kothi',
      'Majhgawan',
      'Nagod',
      'Rampur Baghelan',
      'Rajhurajnagar',
      'Unchehra',
      'Amarpatan',
      'Chitrakoot',
      'Maihar',
      'Uchehara',
    ],
    Sehore: ['Sehore', 'Ashta', 'Budni', 'Ichhawar', 'Nasrullaganj'],
    Seoni: ['Seoni', 'Barghat', 'Chhapara', 'Dhanora', 'Ghansaur', 'Keolari', 'Kurai', 'Lakhnadon'],
    Shahdol: ['Shahdol', 'Beohari', 'Burhar', 'Gohparu', 'Jaisinghnagar', 'Sohagpur'],
    Shajapur: ['Shajapur', 'Agar', 'Badod'],
    Vidisha: ['Vidisha', 'Basoda', 'Gyaraspur', 'Kurwai', 'Lateri', 'Sironj', 'Tyonda'],
  },
  Maharashtra: {
    Ahmednagar: [
      'Akole',
      'Jamkhed',
      'Karjat',
      'Kopargaon',
      'Nagar',
      'Nevasa',
      'Parner',
      'Pathardi',
      'Rahata',
      'Rahuri',
      'Sangamner',
      'Shevgaon',
      'Shrigonda',
      'Shrirampur',
    ],
    Akola: ['Akola', 'Akot', 'Balapur', 'Barshitakli', 'Murtijapur', 'Patur', 'Telhara'],
    Amravati: [
      'Achalpur',
      'Amravati',
      'Anjangaon Surji',
      'Bhatkuli',
      'Chandur Railway',
      'Chandur Bazar',
      'Chikhaldara',
      'Daryapur',
      'Dhamangaon Railway',
      'Dharni',
      'Morshi',
      'Nandgaon Khandeshwar',
      'Teosa',
      'Warud',
    ],
    Aurangabad: [
      'Aurangabad',
      'Gangapur',
      'Kannad',
      'Khuldabad',
      'Paithan',
      'Phulambri',
      'Sillod',
      'Soegaon',
      'Vaijapur',
    ],
    Beed: [
      'Beed',
      'Georai',
      'Majalgaon',
      'Dharur',
      'Wadwani',
      'Parli',
      'Patoda',
      'Ashti',
      'Shirur Kasar',
      'Ambajogai',
      'Kaij',
    ],
    Bhandara: ['Bhandara', 'Lakhandur', 'Lakhani', 'Mohadi', 'Pauni', 'Sakoli', 'Tumsar'],
    Buldhana: [
      'Buldhana',
      'Chikhli',
      'Deulgaon Raja',
      'Jalgaon Jamod',
      'Khamgaon',
      'Lonar',
      'Malkapur',
      'Mehkar',
      'Motala',
      'Nandura',
      'Sangrampur',
      'Shegaon',
      'Sindkhed Raja',
    ],
    Chandrapur: [
      'Chandrapur',
      'Bhadravati',
      'Warora',
      'Chimur',
      'Nagbhir',
      'Bramhapuri',
      'Sindewahi',
      'Mul',
      'Gondpipri',
      'Pombhurna',
      'Saoli',
      'Rajura',
      'Korpana',
      'Jiwati',
      'Ballarpur',
    ],
    Dhule: ['Dhule', 'Sakri', 'Shirpur', 'Sindkheda'],
    Gadchiroli: [
      'Gadchiroli',
      'Etapalli',
      'Armori',
      'Aheri',
      'Korchi',
      'Mulchera',
      'Dharampuri',
      'Bhamragad',
      'Sironcha',
    ],
    Gondia: [
      'Gondia',
      'Tirora',
      'Goregaon',
      'Deori',
      'Amgaon',
      'Salekasa',
      'Arjuni Morgaon',
      'Sadak Arjuni',
    ],
    Hingoli: ['Hingoli', 'Sengaon', 'Kalamnuri', 'Aundha Nagnath', 'Basmath', 'Darwha'],
    Jalna: ['Jalna', 'Ambad', 'Bhokardan', 'Badnapur', 'Partur', 'Mantha', 'Ghansawangi'],
    Jalgaon: [
      'Amalner',
      'Bhadgaon',
      'Bhusawal',
      'Bodwad',
      'Chalisgaon',
      'Chopda',
      'Dharangaon',
      'Erandol',
      'Jalgaon',
      'Jamner',
      'Muktainagar',
      'Pachora',
      'Parola',
      'Raver',
      'Yawal',
    ],
    Kolhapur: [
      'Karveer',
      'Panhala',
      'Shahuwadi',
      'Hatkanangale',
      'Shirol',
      'Gaganbawada',
      'Bhudargad',
      'Radhanagari',
      'Kagal',
      'Gadhinglaj',
      'Ajra',
      'Chandgad',
    ],
    Latur: [
      'Latur',
      'Ausa',
      'Renapur',
      'Deoni',
      'Shirur Anantpal',
      'Jalkot',
      'Ahmadpur',
      'Chakur',
      'Nilanga',
      'Udgir',
    ],
    'Mumbai City': [
      'Byculla',
      'D Ward',
      'E Ward',
      'F/N Ward',
      'F/S Ward',
      'G/N Ward',
      'G/S Ward',
      // (Mumbai City is mostly treated as a single administrative district)
    ],
    'Mumbai Suburban': [
      'Kurla',
      'Andheri',
      'Borivali',
      // (Mumbai Suburban officially has these 3 tehsils)
    ],
    Nagpur: [
      'Nagpur Urban',
      'Nagpur Rural',
      'Hingna',
      'Katol',
      'Savner',
      'Ramtek',
      'Kalameshwar',
      'Narkhed',
      'Parseoni',
      'Umred',
      'Kuhi',
      'Bhiwapur',
    ],
    Nanded: [
      'Nanded',
      'Ardhapur',
      'Bhokar',
      'Biloli',
      'Deglur',
      'Dharmabad',
      'Hadgaon',
      'Himayatnagar',
      'Kinwat',
      'Kandhar',
      'Loha',
      'Mudkhed',
      'Mukhed',
      'Naigaon',
      'Umri',
    ],
    Nandurbar: ['Nandurbar', 'Navapur', 'Akkalkuwa', 'Shahada', 'Taloda', 'Tondapur'],
    Nashik: [
      'Nashik',
      'Igatpuri',
      'Dindori',
      'Kalwan',
      'Deola',
      'Baglan (Satana)',
      'Malegaon',
      'Nandgaon',
      'Niphad',
      'Chandvad',
      'Peint',
      'Surgana',
      'Trimbakeshwar',
      'Yevla',
    ],
    Osmanabad: ['Osmanabad', 'Tuljapur', 'Kalamb', 'Lohara', 'Paranda', 'Umarga', 'Washi'],
    Palghar: ['Palghar', 'Vasai', 'Dahanu', 'Talasari', 'Wada', 'Vikramgad', 'Jawhar', 'Mokhada'],
    Parbhani: [
      'Parbhani',
      'Gangakhed',
      'Jintur',
      'Purna',
      'Sailu',
      'Sonpeth',
      'Manwath',
      'Palam',
      'Pathri',
    ],
    Pune: [
      'Pune City',
      'Haveli',
      'Maval',
      'Mulshi',
      'Shirur',
      'Baramati',
      'Daund',
      'Indapur',
      'Bhor',
      'Velhe',
      'Khed',
      'Junnar',
      'Ambegaon',
      'Purandar',
    ],
    // Raigad: ['Raigad', 'Alibag', 'Panvel', 'Mahad'],
    Ratnagiri: [
      'Ratnagiri',
      'Chiplun',
      'Sangameshwar',
      'Khed',
      'Dapoli',
      'Rajapur',
      'Guhagar',
      'Lanja',
      'Mandangad',
    ],
    Raigad: [
      'Alibag',
      'Panvel',
      'Mahad',
      'Mangaon',
      'Murud',
      'Pen',
      'Roha',
      'Shrivardhan',
      'Tala',
      'Uran',
      'Karjat',
      'Khalapur',
      'Mahad',
      'Mhasla',
      'Poladpur',
      'Sudhagad (Pali)',
    ],
    Satara: [
      'Satara',
      'Karad',
      'Phaltan',
      'Koregaon',
      'Man',
      'Khatav',
      'Patan',
      'Jaoli',
      'Mahabaleshwar',
      'Wai',
    ],
    Sindhudurg: [
      'Sindhudurg (Oros)',
      'Sawantwadi',
      'Vengurla',
      'Malvan',
      'Kankavli',
      'Kudal',
      'Dodamarg',
      'Devgad',
    ],
    Solapur: [
      'Solapur North',
      'Solapur South',
      'Barshi',
      'Mohol',
      'Pandharpur',
      'Sangola',
      'Mangalvedhe',
      'Akkalkot',
      'Malshiras',
      'Karmala',
    ],
    Thane: ['Thane', 'Kalyan', 'Bhiwandi', 'Ulhasnagar', 'Shahapur', 'Murbad', 'Ambarnath'],
    Wardha: [
      'Wardha',
      'Arvi',
      'Hinganghat',
      'Deoli',
      'Seloo',
      'Samudrapur',
      'Ashti',
      'Karanja (Wardha)',
    ],
    Washim: ['Washim', 'Karanja', 'Mangrulpir', 'Manora', 'Risod', 'Malegaon'],
    Yavatmal: [
      'Yavatmal',
      'Pusad',
      'Digras',
      'Wani',
      'Arni',
      'Babulgaon',
      'Darwha',
      'Ghatanji',
      'Kalamb',
      'Mahagaon',
      'Maregaon',
      'Ner',
      'Ralegaon',
      'Umarkhed',
      'Zari-Jamani',
    ],
  },
  Manipur: {
    Bishnupur: ['Nambol', 'Moirang', 'Bishnupur', 'Kangabok', 'Kumbi'],
    Chandel: ['Chandel', 'Sugnu', 'Sekmai', 'Moreh', 'Khengjoy'],
    Churachandpur: ['Churachandpur', 'Lamka', 'Sangrung', 'Tuibong'],
    'Imphal East': ['Porompat', 'Keirao', 'Lamlai', 'Yairipok', 'Kangchup', 'Sawombung'],
    'Imphal West': ['Imphal', 'Patsoi', 'Lamsang', 'Heingang', 'Thongju', 'Wangoi'],
    Jiribam: ['Jiribam', 'Nungba', 'Kachakphung'],
    Kakching: ['Kakching', 'Waikhong', 'Kangla', 'Keibung'],
    Kamjong: ['Kamjong', 'Mao', 'Phungyar', 'Tungbung'],
    Kangpokpi: ['Kangpokpi', 'Saikul', 'Saitu', 'Sadar Hills'],
    Noney: ['Noney', 'Tamenglong', 'Tamei', 'Nungba'],
    Pherzawl: ['Pherzawl', 'Hengbung', 'Khoupum', 'Vangai'],
    Senapati: ['Senapati', 'Tamei', 'Liyai', 'Nungshang', 'Tadubi'],
    Tamenglong: ['Tamenglong', 'Kadilong', 'Tadubi', 'Jiri', 'Laii'],
    Thoubal: ['Thoubal', 'Wangjing', 'Yairipok', 'Khangabok', 'Kakching'],
    Ukhrul: ['Ukhrul', 'Litan', 'Chingai', 'Saitu', 'Maring'],
  },
  Meghalaya: {
    'Eastern West Khasi Hills': ['Mairang', 'Mawthadraishan', 'Nongkhlaw', 'Markasa'],
    'North Garo Hills': ['Resubelpara', 'Kharkutta', 'Bajengdoba', 'Adokgre'],
    'South West Khasi Hills': ['Mawkyrwat', 'Ranikor', 'Warsan Lyngdoh', 'Domiasiat'],
    'West Jaintia Hills': ['Jowai', 'Thadlaskein', 'Amlarem', 'Namdong'],
    'East Garo Hills': ['Williamnagar', 'Sohra', 'Dalu', 'Mendipathar'],
    'East Khasi Hills': ['Shillong', 'Nongstoin', 'Mawkyrwat', 'Pynursla'],
    'Jaintia Hills': ['Jowai', 'Nartiang', 'Amlarem', 'Thadlaskein'],
    'Ri-Bhoi': ['Nongpoh', 'Barapathar', 'Umsning', 'Khasi'],
    'South Garo Hills': ['Baghmara', 'Zikzak', 'Tura', 'Rongram'],
    'South West Garo Hills': ['Mendipathar', 'Tikrikilla', 'Nangalbibra', 'Rajabala'],
    'West Garo Hills': ['Tura', 'Phulbari', 'Nangalbibra', 'Dalu'],
    'West Khasi Hills': ['Mairang', 'Nongstoin', 'Ranikor', 'Mawkyrwat'],
  },
  Mizoram: {
    Aizawl: ['Aizawl', 'Bawngkawn', 'Tlangnuam', 'Durtlang'],
    Champhai: ['Champhai', 'Khawnpui', 'Serchhip', 'Hnahthial'],
    Hnahthial: ['Hnahthial', 'Serchhip', 'Bualpui', 'Bualpui East'],
    Khawzawl: ['Khawzawl', 'Hnahthial', 'Serchhip', 'Champhai'],
    Kolasib: ['Kolasib', 'Bilkhawthlir', 'Bawngkawn', 'Chhimtuipui'],
    Lawngtlai: ['Lawngtlai', 'Siaha', 'Lunglei', 'Mamit'],
    Lunglei: ['Lunglei', 'Serchhip', 'Champhai', 'Lawngtlai'],
    Mamit: ['Mamit', 'Serchhip', 'Lunglei', 'Siaha'],
    Saiha: ['Saiha', 'Lawngtlai', 'Siaha', 'Mamit'],
    Serchhip: ['Serchhip', 'Aizawl', 'Khawzawl', 'Hnahthial'],
  },
  Nagaland: {
    Chümoukedima: ['Chümoukedima', 'Medziphema', 'Seithekema', 'Khaibung'],
    Niuland: ['Niuland', 'Aghunaqa', 'Hokhezhe', 'Khehoi'],
    Shamator: ['Shamator', 'Chessore', 'Sangphur', 'Tsurungto'],
    Tseminyu: ['Tseminyu', 'Ghaspani', 'Kohima Rural', 'Rengma'],
    Noklak: ['Noklak', 'Thonoknyu', 'Panso', 'Chingmei'],
    Dimapur: ['Dimapur', 'Chümoukedima', 'Niuland', 'Peren'],
    Kiphire: ['Kiphire', 'Pungro', 'Saramati', 'Longkhim'],
    Kohima: ['Kohima', 'Chiephobozou', 'Phesama', 'Sechü-Zubza'],
    Mokokchung: ['Mokokchung', 'Longkhum', 'Chuchuyimlang', 'Mangkolemba'],
    Mon: ['Mon', 'Tizit', 'Mokokchung', 'Longwa'],
    Peren: ['Peren', 'Tening', 'Kohima', 'Dimapur'],
    Phek: ['Phek', 'Meluri', 'Kohima', 'Kiphire'],
    Tuensang: ['Tuensang', 'Shamator', 'Longkhim', 'Changsang'],
    Wokha: ['Wokha', 'Chukitong', 'Bokajan', 'Nokia'],
    Zunheboto: ['Zunheboto', 'Satoi', 'Sungro', 'Pungro'],
  },
  Odisha: {
    Angul: ['Angul', 'Talcher', 'Pallahara', 'Chhendipada'],
    Bargarh: ['Bargarh', 'Padampur', 'Barpali', 'Attabira'],
    'Baleswar (Balasore)': ['Baleswar', 'Bhograi', 'Jaleswar', 'Soro'],
    Balangir: ['Balangir', 'Patnagarh', 'Deogaon', 'Loisingha'],
    Boudh: ['Boudh', 'Barkote', 'Harabhanga'],
    Cuttack: ['Cuttack', 'Athagarh', 'Tangi-Choudwar', 'Niali'],
    Dhenkanal: ['Dhenkanal', 'Kamakhyanagar', 'Parajang', 'Kankadahada'],
    Gajapati: ['Gajapati', 'Gumma', 'Mohana', 'R Udayagiri'],
    Ganjam: ['Ganjam', 'Chikiti', 'Brahmapur', 'Sanakhemundi'],
    Jagatsinghpur: ['Jagatsinghpur', 'Balikuda', 'Tirtol', 'Raghunathpur'],
    Jajpur: ['Jajpur', 'Bari', 'Binjharpur', 'Raghunathpur'],
    Jharsuguda: ['Jharsuguda', 'Kirmira', 'Lakhanpur', 'Rengali'],
    Kalahandi: ['Kalahandi', 'Kesinga', 'Kalampur', 'Bhawanipatna'],
    Kandhamal: ['Kandhamal', 'Phulbani', 'Baliguda', 'Daringbadi'],
    Kendrapara: ['Kendrapara', 'Aul', 'Rajkanika', 'Mahakalapada'],
    Keonjhar: ['Keonjhar', 'Barbil', 'Joda', 'Champua'],
    Khurda: ['Khurda', 'Bhubaneswar', 'Jatani', 'Balipatna'],
    Koraput: ['Koraput', 'Jeypore', 'Nandapur', 'Pottangi'],
    Malkangiri: ['Malkangiri', 'Korukonda', 'Malkangiri Rural', 'Khajuripada'],
    Mayurbhanj: ['Mayurbhanj', 'Baripada', 'Rairangpur', 'Karanjia'],
    Nabarangpur: ['Nabarangpur', 'Umarkote', 'Jharigam', 'Raighar'],
    Nayagarh: ['Nayagarh', 'Daspalla', 'Odagaon', 'Khandapada'],
    Nuapada: ['Nuapada', 'Khariar', 'Sinapali', 'Rajgangpur'],
    Puri: ['Puri', 'Satyabadi', 'Nimapada', 'Astaranga'],
    Rayagada: ['Rayagada', 'Kalyansinghpur', 'Padmapur', 'Bissamcuttack'],
    Sambalpur: ['Sambalpur', 'Rairakhol', 'Jharsuguda', 'Naktideul'],
    Sundargarh: ['Sundargarh', 'Rajgangpur', 'Lathikata', 'Bonai'],
  },
  Punjab: {
    Amritsar: ['Ajnala', 'Amritsar-1', 'Amritsar-2', 'Baba Bakala', 'Majitha', 'Lopoke'],
    Barnala: ['Barnala', 'Mehal Kalan', 'Tapa'],
    Bathinda: ['Bathinda', 'Rampura Phul', 'Talwandi Sabo', 'Maur'],
    Faridkot: ['Faridkot', 'Jaito', 'Kot Kapura'],
    'Fatehgarh Sahib': ['Amloh', 'Bassi Pathana', 'Fatehgarh Sahib', 'Khamanon'],
    Fazilka: ['Abohar', 'Fazilka', 'Jalalabad'],
    Firozpur: ['Firozpur', 'Guru Harsahai', 'Zira'],
    Gurdaspur: [
      'Batala',
      'Dera Baba Nanak',
      'Dina Nagar',
      'Fatehgarh Churian',
      'Gurdaspur',
      'Kalanaur',
    ],
    Hoshiarpur: ['Dasua', 'Garhshankar', 'Hoshiarpur', 'Mukerian', 'Tanda'],
    Jalandhar: ['Adampur', 'Jalandhar-1', 'Jalandhar-2', 'Nakodar', 'Phillaur', 'Shahkot'],
    Kapurthala: ['Bhulath', 'Kapurthala', 'Phagwara', 'Sultanpur Lodhi'],
    Ludhiana: ['Jagraon', 'Khanna', 'Ludhiana East', 'Ludhiana West', 'Payal', 'Raikot', 'Samrala'],
    Malerkotla: ['Amargarh', 'Ahmedgarh', 'Malerkotla'],
    Mansa: ['Budhlada', 'Mansa', 'Sardulgarh'],
    Moga: ['Bagha Purana', 'Dharamkot', 'Moga', 'Nihal Singh Wala'],
    Pathankot: ['Dhar Kalan', 'Pathankot'],
    Patiala: ['Dudhan Sadhan', 'Nabha', 'Patiala', 'Patran', 'Rajpura', 'Samana'],
    Rupnagar: ['Anandpur Sahib', 'Chamkaur Sahib', 'Morinda', 'Nangal', 'Rup Nagar'],
    'S.A.S. Nagar(Mohali)': ['S.A.S. Nagar', 'Dera Bassi', 'Kharar'],
    Sangrur: ['Bhawanigarh', 'Dirba', 'Dhuri', 'Lehra', 'Moonak', 'Sangrur', 'Sunam'],
    'Shahid Bhagat Singh Nagar': ['Balachaur', 'Banga', 'Nawan Shahr'],
    'Sri Muktsar Sahib': ['Gidderbaha', 'Malout', 'Sri Muktsar Sahib'],
    'Tarn Taran': ['Bhikhiwind', 'Khadur Sahib', 'Patti', 'Tarn Taran'],
  },
  'Puducherry (UT)': {
    Karaikal: ['Karaikal'],
    Mahe: ['Mahe'],
    Puducherry: ['Puducherry'],
    Yanam: ['Yanam'],
  },
  Rajasthan: {
    Anoopgarh: ['Anoopgarh', 'Rawla', 'Gharsana'],
    Balotra: ['Balotra', 'Baytu', 'Siwana', 'Sindhari', 'Samdari', 'Gida', 'Pachpadra'],
    Beawar: ['Beawar', 'Masuda', 'Raipur', 'Badnor', 'Todgarh'],
    Kekri: ['Kekri', 'Sarwar', 'Baghera', 'Kadera'],
    Deeg: ['Deeg', 'Kaman', 'Nagar'],
    'Didwana-Kuchaman': ['Didwana', 'Kuchaman', 'Makrana', 'Parbatsar'],
    Dudu: ['Dudu', 'Phulera', 'Sambhar'],
    'Gangapur City': ['Gangapur City', 'Bamanwas', 'Khandar'],
    'Jaipur Rural': ['Kotputli', 'Shahpura', 'Viratnagar', 'Jamwa Ramgarh'],
    'Jodhpur Rural': ['Phalodi', 'Osian', 'Shergarh', 'Bhopalgarh'],
    'Kotputli-Behror': ['Kotputli', 'Behror', 'Neemrana', 'Shahpura'],
    'Khairthal-Tijara': ['Khairthal', 'Tijara', 'Bansur'],
    'Neem Ka Thana': ['Neem Ka Thana', 'Khandela', 'Sri Madhopur'],
    Phalodi: ['Phalodi', 'Lohawat', 'Bap'],
    Salumber: ['Salumber', 'Lasadiya', 'Sarada'],
    Sanchore: ['Sanchore', 'Raniwara', 'Bhinmal'],
    Shahpura: ['Shahpura', 'Jahazpur', 'Mandalgarh'],
    Ajmer: ['Ajmer', 'Kekri', 'Pichhola', 'Beawar', 'Nasirabad', 'Pushkar', 'Sarwar', 'Madar'],

    Alwar: ['Alwar', 'Rajgarh', 'Tijara', 'Ramgarh', 'Thanagazi', 'Kathumar', 'Bansur', 'Neemrana'],

    Banswara: ['Banswara', 'Bagidora', 'Arthuna', 'Chhipabarod', 'Kushalgarh', 'Ghatol', 'Garhi'],

    Baran: ['Baran', 'Kishanganj', 'Anta', 'Chhabra', 'Atru', 'Mangrol'],

    Barmer: ['Barmer', 'Balotra', 'Siwana', 'Chohtan', 'Sheo', 'Baytoo', 'Gadra Road', 'Rohat'],

    Bharatpur: ['Bharatpur', 'Nagar', 'Nadbai', 'Kaman', 'Deeg', 'Weir', 'Bayana'],
    Bhilwara: [
      'Bhilwara',
      'Shahpura',
      'Mandal',
      'Banera',
      'Saharan',
      'Hurda',
      'Kotri',
      'Asind',
      'Nathdwara',
      'Mandalgarh',
      'Bijoliya',
      'Gangrar',
    ],

    Bikaner: ['Bikaner', 'Lunkaransar', 'Khajuwala', 'Kolayat', 'Nokha', 'Ratangarh'],

    Bundi: ['Bundi', 'Deoli', 'Indergarh', 'Nainwa', 'Talera', 'Hindoli', 'Keshoraipatan'],

    Chittorgarh: [
      'Chittorgarh',
      'Kapasan',
      'Mandalgarh',
      'Begun',
      'Nimbahera',
      'Gangrar',
      'Bhilwara',
      'Rawatbhata',
    ],

    Churu: ['Churu', 'Rajgarh', 'Ratangarh', 'Sujangarh', 'Taranagar', 'Sardarshahar', 'Bidasar'],
    Dausa: ['Dausa', 'Bandikui', 'Lalsot', 'Mahwa', 'Sikrai', 'Nangal Rajawatan'],
    Dholpur: ['Dholpur', 'Rajakhera', 'Baseri', 'Sarmathura', 'Saipau'],
    Dungarpur: ['Dungarpur', 'Sagwara', 'Simalwara', 'Aspur'],
    Ganganagar: [
      'Sri Ganganagar',
      'Padampur',
      'Suratgarh',
      'Sadulshahar',
      'Karanpur',
      'Raisinghnagar',
    ],
    Hanumangarh: ['Hanumangarh', 'Pilibanga', 'Sangariya', 'Rawatsar', 'Nohar', 'Bhadra'],
    Jaipur: [
      'Jaipur',
      'Amber',
      'Bassi',
      'Chaksu',
      'Chomu',
      'Dudu',
      'Jamwa Ramgarh',
      'Phagi',
      'Phulera',
      'Kotputli',
      'Sanganer',
      'Shahpura',
      'Viratnagar',
    ],
    Jaisalmer: ['Jaisalmer', 'Pokaran', 'Fatehgarh', 'Sam', 'Dechu', 'Ramgarh', 'Baytoo'],

    Jalore: [
      'Jalore',
      'Bhinmal',
      'Sanchore',
      'Ahore',
      'Raniwara',
      'Sardarpura',
      'Bagoda',
      'Jaitpura',
    ],

    Jhalawar: [
      'Jhalawar',
      'Jhalrapatan',
      'Aklera',
      'Pirawa',
      'Khanpur',
      'Bhagwanpura',
      'Manoharthana',
      'Khalilabad',
    ],
    Jhunjhunu: [
      'Jhunjhunu',
      'Alsisar',
      'Khetri',
      'Chirawa',
      'Udaipurwati',
      'Nawalgarh',
      'Surajgarh',
    ],
    Jodhpur: ['Jodhpur', 'Phalodi', 'Luni', 'Bilara', 'Osian', 'Bhopalgarh', 'Shergarh'],
    Karauli: ['Karauli', 'Hindaun', 'Sapotra', 'Mandrail', 'Todabhim', 'Masalpur'],
    Kota: ['Kota', 'Digod', 'Ladpura', 'Pipalda', 'Ramganj Mandi', 'Sangod'],
    Nagaur: ['Nagaur', 'Makrana', 'Degana', 'Merta', 'Ladnun', 'Didwana', 'Khinvsar', 'Parbatsar'],
    Pali: ['Pali', 'Sojat', 'Rani', 'Jaitaran', 'Marwar Junction', 'Bali', 'Sumerpur', 'Raipur'],
    Pratapgarh: ['Pratapgarh', 'Chhoti Sadri', 'Dhariawad', 'Arnod', 'Peepalkhoont'],
    Rajsamand: ['Rajsamand', 'Amet', 'Bhim', 'Deogarh', 'Kumbhalgarh', 'Nathdwara', 'Railmagra'],
    'Sawai Madhopur': [
      'Sawai Madhopur',
      'Bamanwas',
      'Gangapur City',
      'Chouth Ka Barwara',
      'Khandar',
      'Bonli',
    ],
    Sikar: [
      'Sikar',
      'Fatehpur',
      'Laxmangarh',
      'Neem Ka Thana',
      'Danta Ramgarh',
      'Shrimadhopur',
      'Reengus',
    ],
    Sirohi: ['Sirohi', 'Sheoganj', 'Pindwara', 'Reodar', 'Abu Road', 'Mount Abu'],
    Tonk: ['Tonk', 'Malpura', 'Deoli', 'Niwai', 'Peeplu', 'Todaraisingh', 'Uniara'],
    Udaipur: [
      'Udaipur',
      'Kherwara',
      'Gogunda',
      'Sarada',
      'Girwa',
      'Jhadol',
      'Mavli',
      'Salumbar',
      'Rishabhdeo',
      'Kotra',
      'Lasadiya',
    ],
  },
  Sikkim: {
    'East Sikkim': ['Gangtok', 'Namchi', 'Mangan'],
    'West Sikkim': ['Gyalshing', 'Soreng', 'Okhrey'],
    'North Sikkim': ['Mangan', 'Dzongu', 'Kabi Lungri'],
    'South Sikkim': ['Namchi', 'Pemayangtse', 'Jorethang'],
  },
  Telangana: {
    Adilabad: [
      'Adilabad',
      'Bazarhathnoor',
      'Gudihatnur',
      'Ichoda',
      'Inderavelly',
      'Jainad',
      'Kagaznagar',
      'Kerameri',
      'Kouthala',
      'Neradigonda',
      'Nirmal',
      'Tamsi',
      'Utnoor',
    ],
    'Bhadradri Kothagudem': [
      'Aswapuram',
      'Bhadrachalam',
      'Chandrugonda',
      'Dummugudem',
      'Gundala',
      'Kothagudem',
      'Manuguru',
      'Mulakalapally',
      'Pinapaka',
      'Sathupalli',
      'Tekulapalli',
    ],
    Hyderabad: [
      'Amberpet',
      'Asifnagar',
      'Bahadurpura',
      'Bandlaguda',
      'Charminar',
      'Golconda',
      'Himayatnagar',
      'Nampally',
      'Saidabad',
      'Secunderabad',
      'Ameerpet',
      'Khairtabad',
      'Marredpally',
      'Musheerabad',
      'Shaikpet',
      'Tirumalagiri',
    ],
    Jagtial: ['Jagtial', 'Dasnapur', 'Metpally', 'Mallial', 'Korutla', 'Gogulapally'],
    Jangaon: ['Jangaon', 'Zaffergadh', 'Ghanpur', 'Mulugu', 'Raghunathpalle'],
    'Jayashankar Bhupalpally': ['Bhupalpally', 'Chityala', 'Kataram', 'Maripeda', 'Mulug'],
    'Jogulamba Gadwal': ['Gadwal', 'Alampur', 'Kurnool', 'Wanaparthy'],
    Kamareddy: ['Kamareddy', 'Banswada', 'Bodhan', 'Yellareddy'],
    Karimnagar: ['Karimnagar', 'Manakondur', 'Choppadandi', 'Shankarapatnam', 'Huzurabad'],
    Khammam: ['Khammam', 'Kalluru', 'Palair', 'Aswaraopeta', 'Yellandu'],
    'Komaram Bheem Asifabad': ['Komaram Bheem', 'Sirpur', 'Kaghaznagar'],
    Mahabubabad: ['Mahabubabad', 'Thorrur', 'Narsampet'],
    Mahabubnagar: ['Mahabubnagar', 'Kothakota', 'Kodangal', 'Jadcherla', 'Narayanpet'],
    Mancherial: ['Mancherial', 'Mandamarri', 'Bellampalli'],
    Medak: ['Medak', 'Dubbak', 'Kondapak'],
    'Medchal–Malkajgiri': ['Medchal', 'Malkajgiri'],
    Nagarkurnool: ['Nagarkurnool', 'Achampet', 'Kalwakurthy'],
    Nalgonda: ['Nalgonda', 'Miryalaguda', 'Devarakonda'],
    Nirmal: ['Nirmal', 'Morthad', 'Chennur'],
    Nizamabad: ['Nizamabad', 'Bodhan', 'Armoor'],
    Peddapalli: ['Peddapalli', 'Mancherial', 'Srirampur'],
    'Rajanna Sircilla': ['Sircilla', 'Vemulawada', 'Boinpalli'],
    Rangareddy: ['Rajendranagar', 'Shadnagar', 'Chevella'],
    Sangareddy: ['Sangareddy', 'Andole', 'Patancheru'],
    Siddipet: ['Siddipet', 'Gajwel', 'Thoguta'],
    Suryapet: ['Suryapet', 'Huzurnagar', 'Maddirala'],
    Vikarabad: ['Vikarabad', 'Tandur'],
    Wanaparthy: ['Wanaparthy', 'Pebbair'],
    'Warangal (Rural)': ['Mulugu', 'Venkatapur', 'Parkal'],
    'Warangal (Urban)': ['Kazipet', 'Hanamkonda', 'Warangal'],
    'Yadadri Bhuvanagiri': ['Bhuvanagiri', 'Choutuppal', 'Yadagirigutta'],
  },
  TamilNadu: {
    Chennai: [
      'Ambattur',
      'Aminjikarai',
      'Ayanavaram',
      'Egmore',
      'Kolathur',
      'Maduravoyal',
      'Mambalam',
      'Madhavaram',
      'Perambur',
      'Purasawalkam',
      'Sholinganallur',
      'Thiruvottiyur',
      'Tondiarpet',
      'Velachery',
      'Guindy',
      'Alandur',
    ],
    Kancheepuram: ['Kancheepuram', 'Sriperumbudur', 'Uthiramerur', 'Walajabad', 'Kundrathur'],
    Coimbatore: [
      'Annur',
      'Coimbatore (North)',
      'Coimbatore (South)',
      'Kinathukadavu',
      'Madukarai',
      'Mettupalayam',
      'Perur',
      'Pollachi',
      'Sulur',
      'Valparai',
    ],
    Cuddalore: [
      'Bhuvanagiri',
      'Chidambaram',
      'Kattumannarkoil',
      'Kurinjipadi',
      'Panruti',
      'Srimushnam',
      'Thittakudi',
      'Veppur',
      'Virudhachalam',
    ],
    Dharmapuri: [
      'Dharmapuri',
      'Harur',
      'Karimangalam',
      'Nallampalli',
      'Palacode',
      'Pappireddipatti',
      'Pennagaram',
    ],
    Dindigul: [
      'Dindigul East',
      'Dindigul West',
      'Guziliyamparai',
      'Kodaikanal',
      'Natham',
      'Nilgottai',
      'Oddanchatram',
      'Palani',
      'Vedasandur',
    ],
    Erode: [
      'Anthiyur',
      'Bhavani',
      'Gobichettipalayam',
      'Kodumudi',
      'Modakurichi',
      'Nambiyur',
      'Perundurai',
      'Sathiyamangalam',
      'Thalavadi',
    ],
    Kanniyakumari: ['Agasteeswaram', 'Kalkulam', 'Killiyur', 'Thovalai', 'Vilavancode'],
    Karur: [
      'Karur',
      'Aravakurichi',
      'Kadavur',
      'Krishnarayapuram',
      'Kulithalai',
      'Manmangalam',
      'Pugalur',
    ],
    Madurai: [
      'Madurai East',
      'Madurai North',
      'Madurai South',
      'Madurai West',
      'Melur',
      'Peraiyur',
      'Thirumangalam',
      'Thiruparankundram',
      'Usilampatti',
      'Vadipatti',
    ],
    Nagapattinam: ['Nagapattinam', 'Kilvelur', 'Thirukkuvalai', 'Vedaranyam'],
    Namakkal: [
      'Namakkal',
      'Kumarapalayam',
      'Mohandur',
      'Paramathi Velur',
      'Rasipuram',
      'Senthamangalam',
      'Tiruchengode',
    ],
    Nilgiris: ['Udagamandalam', 'Coonoor', 'Gudalur', 'Kothagiri', 'Kundah', 'Pandalur'],
    Perambalur: ['Perambalur', 'Alathur', 'Kunnam', 'Veppanthattai'],
    Pudukkottai: [
      'Aranthangi',
      'Avudaiarkoil',
      'Gandarvakottai',
      'Iluppur',
      'Karambakudi',
      'Kulathur',
      'Manamelkudi',
      'Ponnamaravathi',
      'Thirumayam',
      'Viralimalai',
    ],
    Ramanathapuram: [
      'Ramanathapuram',
      'Kadaladi',
      'Kamuthi',
      'Mudukulathur',
      'Paramakudi',
      'Rajasingamangalam',
      'Rameswaram',
      'Tiruvadanai',
    ],
    Salem: [
      'Attur',
      'Edappadi',
      'Gangavalli',
      'Kadaiyampatti',
      'Mettur',
      'Omalur',
      'Pethanayakanpalayam',
      'Salem South',
      'Salem West',
      'Sankari',
      'Vazhapadi',
      'Yercaud',
    ],
    Sivagangai: [
      'Devakottai',
      'Ilayankudi',
      'Karaikudi',
      'Manamadurai',
      'Singampunari',
      'Tirupuvanam',
      'Tirupathur',
    ],
    Thanjavur: [
      'Thanjavur',
      'Boothalur',
      'Kumbakonam',
      'Orathanadu',
      'Papanasam',
      'Pattukottai',
      'Peravurani',
      'Thiruvidaimaruthur',
    ],
    Theni: ['Aandipatti', 'Bodinayakanur', 'Periyakulam', 'Uthamapalayam'],
    Thiruvarur: [
      'Thiruvarur',
      'Kodavasal',
      'Koothanallur',
      'Mannargudi',
      'Nannilam',
      'Needamangalam',
      'Thiruthuraipoondi',
      'Valangaiman',
    ],
    Thoothukudi: [
      'Eral',
      'Ettayapuram',
      'Kayathar',
      'Kovilpatti',
      'Ottapidaram',
      'Srivaikundam',
      'Tiruchendur',
      'Vilathikulam',
    ],
    Tiruchirapalli: [
      'Lalgudi',
      'Manachanallur',
      'Manapparai',
      'Marungapuri',
      'Musiri',
      'Srirangam',
      'Thottiam',
      'Thuraiyur',
      'Tiruchirappalli East',
      'Tiruchirappalli West',
      'Tiruverumbur',
    ],
    Tirunelveli: [
      'Ambasamudram',
      'Cheranmahadevi',
      'Manur',
      'Nanguneri',
      'Palayamkottai',
      'Radhapuram',
      'Thisayanvilai',
    ],
    Tiruvallur: [
      'Avadi',
      'Gummidipoondi',
      'Pallipattu',
      'Ponneri',
      'Poonamallee',
      'R.K. Pet',
      'Tiruttani',
      'Tiruvallur',
      'Uthukottai',
    ],
    Tiruvannamalai: [
      'Arni',
      'Chengam',
      'Chetpet',
      'Cheyyar',
      'Jamunamarathoor',
      'Kalasapakkam',
      'Kilpennathur',
      'Polur',
      'Thandaramapattu',
      'Tiruvannamalai',
    ],
    Tiruvarur: [
      'Thiruvarur',
      'Kodavasal',
      'Koothanallur',
      'Mannargudi',
      'Nannilam',
      'Needamangalam',
      'Thiruthuraipoondi',
      'Valangaiman',
    ],
    Vellore: [
      'Arakkonam',
      'Arcot',
      'Gudiyatham',
      'Katpadi',
      'Pernambut',
      'Velore', // sometimes spelled “Vellore”
    ],
    Villupuram: ['Villupuram', 'Kallakurichi', 'Tirukkoyilur', 'Tindivanam', 'Vanur'],
    Virudhunagar: [
      'Virudhunagar',
      'Aruppukottai',
      'Rajapalayam',
      'Sattur',
      'Srivilliputhur',
      'Tiruchuli',
      'Vembakkottai',
      'Watrap',
    ],
  },
  Tripura: {
    Dhalai: ['Ambassa', 'Kamalpur', 'Teliamura', 'Madhabpur', 'Barpathari'],
    Gomati: ['Udaipur', 'Amarpur', 'Karbook', 'Kailasahar'],
    Khowai: ['Khowai', 'Dasda', 'Kalyanpur'],
    'North Tripura': ['Dharmanagar', 'Kanchanpur', 'Panisagar', 'Kadamtala'],
    Sepahijala: ['Sonamura', 'Bishalgarh', 'Melaghar'],
    'South Tripura': ['Belonia', 'Santirbazar', 'Rajapur'],
    Unakoti: ['Kailashahar', 'Kamalpur', 'Kanchanpur'],
    'West Tripura': ['Agartala', 'Bishalgarh', 'Boxanagar', 'Jirania'],
  },
  'Uttar Pradesh': {
    Ayodhya: [
      'Ayodhya Sadar',
      'Rudauli',
      'Bikapur',
      'Sohawal',
      'Milkipur',
      'Amaniganj',
      'Bikapur',
      'Hariyangatanganj',
      'Masodha',
      'Mawai',
      'Maya Bazar',
      'Milkipur',
      'Pura Bazar',
      'Rudauli',
      'Sohawal',
      'Tarun',
    ],
    Balrampur: [
      'Balrampur',
      'Tulsipur',
      'Utraula',
      'Balrampur',
      'Gaindas Bujurg',
      'Gainsari',
      'Harriya Satgharwa',
      'Pachpedwa',
      'Rehra Bazar',
      'Shriduttganj',
      'Tulsipur',
      'Utraula',
    ],
    Banda: [
      'Atarra',
      'Baberu',
      'Banda',
      'Naraini',
      'Pailani',
      'Baberu',
      'Badokhar Khurd',
      'Bisanda',
      'Jaspura',
      'Kamasin',
      'Mahuva',
      'Pailani',
      'Banda',
      'Naraini',
    ],
    Bhadohi: [
      'Aurai',
      'Bhadohi',
      'Gyanpur',
      'Abholi',
      'Deegh',
      'Suriyawan',
      'Gyanpur',
      'Aurai',
      'Bhadohi',
    ],
    Chandauli: [
      'Chandauli Sadar',
      'Sakaldiha',
      'Chakia',
      'Mughalsarai',
      'Naugarh',
      'Barahani',
      'Chandauli',
      'Niyamatabad',
      'Chahaniya',
      'Sakaldiha',
      'Dhanapur',
      'Chakia',
      'Shahabganj',
      'Naugarh',
    ],
    Chitrakoot: ['Chitrakoot', 'Karwi', 'Chitrakoot', 'Karwi'],
    Deoria: [
      'Deoria Sadar',
      'Salempur',
      'Barhaj',
      'Bhatpar Rani',
      'Rampur Karkhana',
      'Bhalauli',
      'Chhitauni',
      'Deoria',
      'Junube',
      'Nanpara',
      'Salempur',
      'Belrayan',
      'Sandahi',
      'Sikrahna',
    ],
    Etah: [
      'Etah',
      'Aliganj',
      'Baran',
      'Bhagwant Nagar',
      'Etah Sadar',
      'Jaswantganj',
      'Kasganj',
      'Jaswantganj',
      'Malawan',
    ],
    Farrukhabad: [
      'Farrukhabad',
      'Kanjhauli',
      'Kaimganj',
      'Kaimganj (Town)',
      'Farrukhabad Bandh',
      'Shikohabad',
      'Salarpur',
    ],
    Firozabad: ['Firozabad', 'Tundla', 'Shahganj', 'Firozabad', 'Rajgram', 'Shahganj'],
    'Gautam Buddha Nagar': ['Dadri', 'Bisrakh', 'Dankaur', 'Jewar', 'Noida'],
    Gonda: ['Gonda Sadar', 'Colonelganj', 'Tarabganj', 'Mankapur'],
    Hapur: ['Hapur Sadar', 'Garhmukteshwar', 'Dhaulana'],
    Kannauj: ['Kannauj Sadar', 'Tirwa', 'Chhibramau'],
    Kasganj: ['Kasganj Sadar', 'Patiyali', 'Soron'],
    Kaushambi: ['Chail', 'Manjhanpur', 'Sirathu'],
    Kushinagar: ['Kushinagar Sadar', 'Padrauna', 'Hata', 'Tamkuhi Raj'],
    Lalitpur: ['Lalitpur', 'Mahroni', 'Talbehat', 'Madaawra', 'Pali'],
    Maharajganj: ['Maharajganj Sadar', 'Nautanwa', 'Pharenda', 'Nichlaul'],
    Mahoba: ['Mahoba Sadar', 'Charkhari', 'Kulpahar'],
    Mainpuri: ['Mainpuri Sadar', 'Bhongaon', 'Karhal'],
    Mathura: ['Mathura Sadar', 'Chhata', 'Mant', 'Mahavan'],
    Mau: ['Mau Sadar', 'Ghosi', 'Muhammadabad Gohna'],
    Mirzapur: ['Mirzapur Sadar', 'Chunar', 'Lalganj'],
    Pilibhit: ['Pilibhit Sadar', 'Bisalpur', 'Puranpur'],
    Rampur: ['Rampur Sadar', 'Bilaspur', 'Milak'],
    Sambhal: ['Sambhal Sadar', 'Chandausi', 'Gunnaur'],
    'Sant Kabir Nagar': ['Sant Kabir Nagar Sadar', 'Mehndawal', 'Khalilabad'],
    Shahjahanpur: ['Shahjahanpur Sadar', 'Tilhar', 'Powayan', 'Jalalabad'],
    Shamli: ['Shamli Sadar', 'Kairana', 'Thana Bhawan'],
    Shravasti: ['Shravasti Sadar', 'Ikauna', 'Bhinga'],
    Siddharthnagar: ['Siddharthnagar Sadar', 'Bansi', 'Dumariyaganj', 'Itwa'],
    Sultanpur: ['Sultanpur Sadar', 'Kadipur', 'Lambhua'],
    Varanasi: [
      'Varanasi Sadar',
      'Pindra',
      'Rajatalab',
      'Arajiline',
      'Baragaon',
      'Chiraigaon',
      'Cholapur',
      'Harhua',
      'Kashi Vidyapeeth',
      'Pindra',
      'Sevapuri',
    ],
    Agra: [
      'Agra Sadar',
      'Kiraoli',
      'Etmadpur',
      'Etmadpur',
      'Fatehabad',
      'Bah',
      'Achhnera',
      'Akola',
      'Bichpuri',
      'Shamshabad',
      'Kheragarh',
      'Fatehabad',
      'Etmadpur',
      'Jagner',
      'Barauli Ahir',
      'Saiyan',
      'Bah',
      'Pinahat',
    ],
    Aligarh: [
      'Aligarh Sadar (Koil)',
      'Khair',
      'Atrauli',
      'Iglas',
      'Gabhana',
      'Tappal',
      'Chandaus',
      'Jawan',
      'Lodha',
      'Dhanipur',
      'Gonda',
      'Bijauli',
      'Gangiri',
      'Akrabad',
    ],

    'Allahabad (Prayagraj)': [
      'Prayagraj Sadar',
      'Bara',
      'Handia',
      'Karchhana',
      'Koraon',
      'Meja',
      'Phulpur',
      'Soraon',
      'Jasra',
      'Shankargarh',
      'Pratappur',
      'Saidabad',
      'Dhanupur',
      'Chaka',
      'Kaundhiyara',
      'Uruwa',
      'Manda',
      'Bahariya',
      'Bahadurpur',
      'Sahson',
      'Kaurihar',
      'Shringverpur Dham',
      'Bhagwatpur',
      'Holagarh',
      'Mauaima',
    ],

    'Ambedkar Nagar': [
      'Akbarpur',
      'Tanda',
      'Jalalpur',
      'Alapur',
      'Bhiti',
      'Katehari',
      'Baskhari',
      'Ramnagar',
      'Jahangir Ganj',
      'Bhiyaon',
    ],

    Amethi: [
      'Gauriganj',
      'Lalganj',
      'Jagdishpur',
      'Amethi',
      'Musafirkhana',
      'Tiloi',
      'Bazar Shukul',
      'Bhetua',
      'Bhadar',
      'Sangrampur',
      'Shahgarh',
      'Jamo',
      'Singhpur',
      'Bahadurpur',
    ],
    Amroha: [
      'Amroha Sadar',
      'Dhanaura',
      'Hasanpur',
      'Naugaon Sadat',
      'Amroha',
      'Gajraula',
      'Naugawan Sadat',
      'Joya',
    ],

    Auraiya: [
      'Auraiya Sadar',
      'Bidhuna',
      'Ajitmal',
      'Bhagyanagar',
      'Sahar',
      'Achalda',
      'Erwakatra',
    ],

    Azamgarh: [
      'Azamgarh Sadar',
      'Burhanpur',
      'Lalganj',
      'Mehnagar',
      'Nizamabad',
      'Phulpur',
      'Sagri',
      'Ahiraula',
      'Atrauliya',
      'Azimatgarh',
      'Bilariyaganj',
      'Hariya',
      'Jahanaganj',
      'Koilsa',
      'Maharajganj',
      'Martinganj',
      'Mirzapur',
      'Mohammadpur',
      'Pahnha',
      'Pawai',
      'Rani Ki Sarai',
      'Sathiyaon',
      'Tehbarpur',
      'Tarwa',
      'Thekma',
    ],

    Baghpat: ['Baghpat Sadar', 'Baraut', 'Khekra', 'Pilana', 'Binauli', 'Chhaprauli'],

    Bahraich: [
      'Bahraich Sadar',
      'Kaisarganj',
      'Mahasi',
      'Nanpara',
      'Motipur (Mihinpurwa)',
      'Payagpur',
      'Huzurpur',
      'Pakharpur',
      'Chittaura',
      'Shivpur',
      'Risia',
      'Visheshwarganj',
      'Jarwal',
      'Nawabganj',
      'Tejwapur',
      'Balha',
    ],
    Ballia: [
      'Ballia Sadar',
      'Bansdih',
      'Sikandeh',
      'Belthara',
      'Rasra',
      'Chandpur',
      'Chandapur',
      'Ballia Nagar',
      'Narahi',
    ],

    Barabanki: [
      'Barabanki Sadar',
      'Lekhrajpur',
      'Haidergarh',
      'Ram Nagar',
      'Haidergarh',
      'Masodha',
      'Huzurpur',
      'Dewa',
      'Mahmoodabad',
      'Fatehpur',
    ],

    Bareilly: [
      'Bareilly Sadar',
      'Baheri',
      'Meerganj',
      'Aonla',
      'Bithari Chainpur',
      'Faridpur',
      'Baheri',
      'Mirganj',
    ],

    Basti: [
      'Basti Sadar',
      'Kaptanganj',
      'Salempur',
      'Basti',
      'Harraiya',
      'Mahadewa',
      'Mancchhana',
      'Sadar Bazar',
    ],

    Bijnor: ['Bijnor Sadar', 'Noorpur', 'Dhampur', 'Najibabad', 'Kashipur', 'Rudrapur', 'Nagina'],

    Budaun: [
      'Budaun Sadar',
      'Bisalpur',
      'Ujhani',
      'Dataganj',
      'Sahaswan',
      'Bisauli',
      'Islamnagar',
      'Sikandra Rao',
    ],
    Bulandshahr: [
      'Bulandshahr Sadar',
      'Khara',
      'Shikarpur',
      'Anupshahr',
      'Debai',
      'Bharatpur',
      'Syana',
      'Ahar',
      'Joya',
    ],

    Etawah: [
      'Etawah Sadar',
      'Basrehar',
      'Saifai',
      'Bharthana',
      'Goshainganj',
      'Sikandra Rao',
      'Chhibramau',
      'Kishni',
    ],

    Fatehpur: [
      'Fatehpur Sadar',
      'Bindki',
      'Khaga',
      'Bilhaur',
      'Dibiyapur',
      'Koraon',
      'Dhanapur',
      'Ahraura',
    ],

    Ghaziabad: [
      'Ghaziabad Sadar',
      'Modinagar',
      'Muradnagar',
      'Loni',
      'Khekra',
      'Sahibabad',
      'Vasundhara',
      'Noida',
    ],

    Ghazipur: [
      'Ghazipur Sadar',
      'Zamania',
      'Mohammadabad',
      'Dildarnagar',
      'Jakhanian',
      'Sevrai',
      'Kamsaar',
    ],

    Gorakhpur: [
      'Gorakhpur Sadar',
      'Uttar (City)',
      'Nautanwa',
      'Khorabar',
      'Campierganj',
      'Pipraich',
      'Sahjanwa',
      'Lakshmipur',
      'Campierganj',
    ],

    Hamirpur: ['Hamirpur Sadar', 'Sarila', 'Maudaha', 'Khamaria', 'Mahroni', 'Ghorawal'],
    Hardoi: [
      'Hardoi Sadar',
      'Mallawan',
      'Pihani',
      'Sandila',
      'Shahabad',
      'Sawayajpur',
      'Mahmudabad',
      'Sandi',
      'Beniganj',
      'Kachhauna',
    ],

    Hathras: [
      'Hathras Sadar',
      'Sadabad',
      'Sikandra Rao',
      'Mahamaya Nagar',
      'Sadabad',
      'Sikandra Rao',
      'Hasayan',
    ],

    Jhansi: [
      'Jhansi Sadar',
      'Mauranipur',
      'Jhansi Cantt',
      'Teonthar',
      'Babina',
      'Moth',
      'Garautha',
    ],

    Jalaun: ['Jalaun Sadar', 'Orai', 'Kalpi', 'Konch', 'Madhogarh', 'Auraiya'],

    Jaunpur: [
      'Jaunpur Sadar',
      'Machhli Shahar',
      'Mariahu',
      'Badlapur',
      'Kerakat',
      'Shahganj',
      'Janghai',
    ],

    'Kanpur Nagar': [
      'Kanpur Sadar',
      'Kalyanpur',
      'Auraiya',
      'Sihawal',
      'Bilhaur',
      'Ghatampur',
      'Sarsaul',
      'Bithoor',
    ],

    'Kanpur Dehat': [
      'Akbarpur',
      'Ghatampur',
      'Derapur',
      'Rasulabad',
      'Bilhaur',
      'Jhinjhak',
      'Maitha',
    ],
    Lucknow: [
      'Lucknow Sadar',
      'Malihabad',
      'Sultanpur',
      'Bakshi Ka Talab',
      'Mal',
      'Mohan',
      'Sarojini Nagar',
      'Kaiserganj',
      'Mahona',
    ],

    Meerut: [
      'Meerut Sadar',
      'Garh',
      'Modinagar',
      'Daurala',
      'Mawana',
      'Meerut',
      'Machhara',
      'Jani',
    ],

    Moradabad: [
      'Moradabad Sadar',
      'Sambhal',
      'Chandausi',
      'Bilari',
      'Thakurdwara',
      'Chandpur',
      'Kanth',
      'Rustamnagar',
    ],

    Muzaffarnagar: [
      'Muzaffarnagar Sadar',
      'Budhana',
      'Shamli',
      'Jansath',
      'Thanabhawan',
      'Khatauli',
      'Nagina',
      'Kairana',
    ],

    Pratapgarh: [
      'Pratapgarh Sadar',
      'Raniganj',
      'Kunda',
      'Bodh Gaya',
      'Kunda',
      'Kaushambi',
      'Lohara',
    ],

    Prayagraj: ['Prayagraj Sadar', 'Bara', 'Hanumanganj', 'Karchana', 'Meja', 'Soraon', 'Shahganj'],

    Raebareli: [
      'Raebareli Sadar',
      'Salon',
      'Jais',
      'Unchahar',
      'Dalmau',
      'Bachhrawan',
      'Mahmudabad',
    ],

    Saharanpur: [
      'Saharanpur Sadar',
      'Deoband',
      'Nakud',
      'Behat',
      'Nanauta',
      'Rampur Maniharan',
      'Gangoh',
    ],

    Sitapur: [
      'Sitapur Sadar',
      'Misrikh',
      'Maharajganj',
      'Biswan',
      'Laharpur',
      'Sidhauli',
      'Jalalabad',
    ],

    Sonbhadra: [
      'Robertsganj',
      'Chopan',
      'Dudhi',
      'Ghorawal',
      'Vishnuprayag',
      'Sunderpur',
      'Mirzapur',
      'Raghunathpur',
    ],
    'Lakhimpur Kheri': [
      'Lakhimpur',
      'Phoolbehar',
      'Nakaha',
      'Gola Gokarannath',
      'Behjam',
      'Mohammadi',
      'Pasgawan',
      'Mitauli',
      'Dhaurahara',
      'Issanagar',
      'Palia',
      'Bijuwa',
      'Nighasan',
      'Ramiyabehar',
      'Bankeyganj',
    ],
    '': [''],
  },
  Uttarakhand: {
    Almora: [
      'Almora',
      'Bhikiyasain',
      'Bhanoli',
      'Chaukhutiya',
      'Dwarahat',
      'Jainti',
      'Ranikhet',
      'Someshwar',
      'Syalde',
    ],
    Bageshwar: ['Bageshwar', 'Dug Nakuri', 'Garur', 'Kanda', 'Kapkot'],
    Champawat: ['Champawat', 'Barakot', 'Lohaghat', 'Pati', 'Purnagiri'],
    Chamoli: [
      'Chamoli',
      'Gairsain',
      'Joshimath',
      'Karnaprayag',
      'Nandaprayag',
      'Pokhari',
      'Tharali',
      'Adi Badri',
      'Ghat',
      'Jilasu',
      'Narayanbagar',
    ],
    Dehradun: ['Dehradun', 'Chakrata', 'Doiwala', 'Kalsi', 'Rishikesh', 'Tyuni', 'Vikasnagar'],
    Haridwar: ['Haridwar', 'Laksar', 'Roorkee', 'Bhagwanpur'],
    Nainital: [
      'Nainital',
      'Haldwani',
      'Kaladhungi',
      'Ramgarh',
      'Betalghat',
      'Dhari',
      'Khansyun',
      'Lalkuan',
      'Koshyankutoli',
    ],
    'Pauri Garhwal': [
      'Pauri',
      'Kotdwara',
      'Lansdowne',
      'Satpuli',
      'Srinagar',
      'Thalisain',
      'Yamkeshwar',
      'Bironkhal',
      'Chakisain',
      'Chaubattakhal',
      'Dhumakot',
      'Jakhanikhal',
      'Rikhanikhal',
    ],
    Pithoragarh: [
      'Pithoragarh',
      'Dharchula',
      'Didihat',
      'Gangolihat',
      'Kanalichhina',
      'Munsiari',
      'Berinag',
      'Dharampur',
      'Bangapani',
      'Tejam',
      'Devalthal',
      'Thal',
    ],
    Rudraprayag: ['Rudraprayag', 'Jakholi', 'Ukhimath', 'Basukedar'],
    'Tehri Garhwal': [
      'Tehri',
      'Devprayag',
      'Dhanaulti',
      'Kirtinagar',
      'Narendranagar',
      'Pratapnagar',
      'Balganga',
      'Gaja',
      'Ghansali',
      'Jakhanidhar',
      'Nainbagh',
      'Paoki Devi',
      'Madannegi',
      'Dhanulti',
    ],
    'Udham Singh Nagar': [
      'Rudrapur',
      'Kashipur',
      'Haldwani',
      'Sitarganj',
      'Jaspur',
      'Bajpur',
      'Khatima',
      'Gadarpur',
      'Nanakmatta',
    ],
    Uttarkashi: [
      'Uttarkashi',
      'Barkot',
      'Chinyalisaur',
      'Dunda',
      'Mori',
      'Joshiyara',
      'Purola',
      'Bhatwari',
    ],
  },
  'West Bengal': {
    Alipurduar: ['Alipurduar Sadar', 'Mathabhanga', 'Dinhata'],
    Bankura: ['Bankura Sadar', 'Bishnupur', 'Khatra'],
    Birbhum: ['Suri Sadar', 'Rampurhat', 'Bolpur'],
    'Cooch Behar': ['Cooch Behar Sadar', 'Tufanganj', 'Dinhata', 'Mekhliganj'],
    'Dakshin Dinajpur': ['Balurghat', 'Gangarampur'],
    Darjeeling: ['Darjeeling Sadar', 'Kurseong', 'Mirik', 'Siliguri'],
    Hooghly: ['Chinsurah Sadar', 'Arambagh', 'Chandannagore', 'Srirampore'],
    Howrah: ['Howrah Sadar', 'Uluberia'],
    Jalpaiguri: ['Jalpaiguri Sadar', 'Malbazar', 'Dhupguri'],
    Jhargram: ['Jhargram Sadar'],
    Kalimpong: ['Kalimpong Sadar'],
    Kolkata: ['Kolkata North', 'Kolkata South'],
    Malda: ['Malda Sadar', 'Chanchal'],
    Murshidabad: ['Berhampore', 'Domkal', 'Jangipur', 'Kandi', 'Lalbag'],
    Nadia: ['Krishnanagar Sadar', 'Kalyani', 'Ranaghat', 'Tehatta'],
    'North 24 Parganas': ['Barasat Sadar', 'Barrackpore', 'Basirhat', 'Bangaon', 'Bidhannagar'],
    'Paschim Bardhaman': ['Asansol Sadar', 'Durgapur'],
    'Paschim Medinipur': ['Medinipur Sadar', 'Kharagpur', 'Ghatal'],
    'Purba Bardhaman': ['Bardhaman Sadar North', 'Bardhaman Sadar South', 'Kalna', 'Katwa'],
    'Purba Medinipur': ['Tamluk', 'Haldia', 'Contai', 'Egra'],
    Purulia: ['Purulia Sadar', 'Jhalda', 'Manbazar', 'Raghunathpur'],
    'South 24 Parganas': ['Alipore Sadar', 'Baruipur', 'Canning', 'Diamond Harbour', 'Kakdwip'],
    'Uttar Dinajpur': ['Raiganj', 'Islampur'],
  },
};
export const helpdata: { icon: string; title: string; text: string }[] = [
  {
    icon: "/images/help/hiring.svg",
    title: "Hire Workers Quickly",
    text: "Find skilled, semi-skilled, and unskilled workers easily for factories, warehouses, construction sites, farms, workshops, and household needs."
  },
  {
    icon: "/images/help/workforce.svg",
    title: "Access a Large Workforce",
    text: "Connect with a large pool of workers and manpower suppliers across 30+ categories, helping you find the right workforce for every type of job."
  },
  {
    icon: "/images/help/connection.svg",
    title: "Direct Employer-Worker Connection",
    text: "BookMyWorker simplifies hiring by connecting employers directly with workers, making recruitment faster, transparent, and more reliable."
  },
];

export const CauseData: {
  image: string;
  title: string;
  slug: string;
  text: string;
  raised: string;
  goal: string;
}[] = [
  {
    image: "/images/causes/cause-1.jpg",
    title: "Give medical related help for african children",
    slug: "cause-1",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-2.jpg",
    title: "Give small bunch of colors to little kids, joy of colors",
    slug: "cause-2",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-3.jpg",
    title: "Send poor children to school to become superhero",
    slug: "cause-3",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-4.jpg",
    title: "Uniting Hearts and Minds through Healthcare Outreach",
    slug: "cause-4",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-5.jpg",
    title: "Auctioning Masterpieces to Support Arts Education in Schools",
    slug: "cause-5",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-6.jpg",
    title: "Medical Mission Providing Care in Underserved Communities",
    slug: "cause-6",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-7.jpg",
    title: "Empowering Women and Girls Through Education Initiatives",
    slug: "cause-7",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-8.jpg",
    title: "Harnessing Renewable Energy for Environmental Conservation",
    slug: "cause-8",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
  {
    image: "/images/causes/cause-9.jpg",
    title: "A Fundraising Gala for Education Equality and Access",
    slug: "cause-9",
    text: "You can relay on our amazing features list and also our customer services will be great experience.",
    raised: "$65,360",
    goal: "$124,500",
  },
];

export const Eventdata: {
  image: string;
  title: string;
  text: string;
  date: string;
  location: string;
  type: string;
  entrants: string;
  duration: string;
  category: string;
  detail: string;
  slug: string;
}[] = [
  {
    image: "/images/event/event-1.jpg",
    title: "You should have eagle’s eye on new trends and techonogies",
    slug: "event-1",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
  {
    image: "/images/event/event-2.jpg",
    title: "New Seminar on Newest Food Recipe from World’s Best",
    slug: "event-2",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
  {
    image: "/images/event/event-3.jpg",
    title: "Learn from small things to create something bigger.",
    slug: "event-3",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
  {
    image: "/images/event/event-4.jpg",
    title: "Literary Escapade Book Reading and Discussion.",
    slug: "event-4",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
  {
    image: "/images/event/event-5.jpg",
    title: "A Journey Through Time Historical Reenactment Fair.",
    slug: "event-5",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
  {
    image: "/images/event/event-6.jpg",
    title: "Leadership Summit Empowering Tomorrow's Leaders.",
    slug: "event-6",
    text: "Business Park, Opp. Corns Sam Restaurant, New Yoark, US",
    date: "May 10, 2024",
    location: "San Marcos",
    type: "Open",
    entrants: "Unlimited",
    duration: "1655 Days",
    category: "Calendar, Dontaions",
    detail:
      "Donec hendrerit, dui quis ultricies eleifend, ipsum sapien auctor ligula, vitae interdum augue metus nec sem. Pellentesque mollis ex risus, eget dignissim nibh fermentum in. Cras eu ipsum eget ante ullamcorper vehicula. Suspendisse non blandit mi.Mauris eu sapien urna. Fusce eu luctus augue, non vestibulum felis. Fusce sollicitudin porta augue non porta. Vivamus ullamcorper tristique nisi, in mattis elit porta vitae. Curabitur euismod lectus non maximus dictum. Vivamus luctus, eros at posuere",
  },
];

export const footerLinks: { link: string }[] = [
  {
    link: "Medical crowdfunding",
  },
  {
    link: "Cancer Crowdfunding",
  },
  {
    link: "Transplant Crowdfunding",
  },
  {
    link: "Education Crowdfunding",
  },
  {
    link: "Child Welfare",
  },
  {
    link: "Medical Finance",
  },
  {
    link: "FAQs & Help Center",
  },
  {
    link: "Fundraiser Video",
  },
  {
    link: "Trust & Safety",
  },
  {
    link: "Plans & Pricing*",
  },
];

export const Reviews: {
  clientImg: string;
  clientName: string;
  review: string;
  post: string;
}[] = [
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Rajesh Sharma",
    review:
      "BookMyWorker helped us find reliable construction workers quickly. The platform makes it easy to connect directly with manpower suppliers and manage workforce requirements without delays.",
    post: "Construction Contractor",
  },
  {
    clientImg: "/images/testimonial/client-2.jpg",
    clientName: "Anil Verma",
    review:
      "We regularly hire factory helpers and machine operators through this platform. The process is simple and we get workers faster compared to traditional hiring methods.",
    post: "Factory Owner",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Sunita Gupta",
    review:
      "Finding trustworthy domestic workers was always difficult. Through this platform we connected with verified suppliers and hired house help within a short time.",
    post: "Household Employer",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Mohit Agarwal",
    review:
      "Our warehouse operations require daily manpower. BookMyWorker allows us to connect with multiple manpower suppliers and arrange workers quickly whenever required.",
    post: "Warehouse Manager",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Vikas Singh",
    review:
      "For our farm we needed seasonal labor during harvesting. Using this platform we were able to contact worker suppliers easily and manage our farm workforce smoothly.",
    post: "Farm Owner",
  },
  {
    clientImg: "/images/testimonial/client-2.jpg",
    clientName: "Neha Khanna",
    review:
      "The biggest advantage is that employers can directly connect with manpower suppliers. It saves time and helps us get the right workers for our projects.",
    post: "Operations Manager",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Rohit Tiwari",
    review:
      "We hired electricians, plumbers, and helpers for multiple projects through this platform. It is convenient to find skilled and semi-skilled workers in one place.",
    post: "Real Estate Developer",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Arvind Patel",
    review:
      "BookMyWorker is a very useful platform for businesses. Whether it is loading workers, drivers, or helpers, we can find manpower quickly without long searches.",
    post: "Logistics Business Owner",
  },
  {
    clientImg: "/images/testimonial/client-2.jpg",
    clientName: "Kiran Mehta",
    review:
      "We often require event setup workers and tent house labor. Through this platform we easily connect with suppliers and arrange workers even on short notice.",
    post: "Event Organizer",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Deepak Yadav",
    review:
      "This platform simplifies hiring. Employers from different industries can find the right workers without unnecessary complications. It has saved us a lot of time.",
    post: "Manufacturing Unit Owner",
  },
  {
    clientImg: "/images/testimonial/client-2.jpg",
    clientName: "Priya Sinha",
    review:
      "BookMyWorker helped us hire housekeeping and cleaning staff for our office facility. The workers were arranged quickly through trusted manpower suppliers.",
    post: "Facility Manager",
  },
  {
    clientImg: "/images/testimonial/client-1.jpg",
    clientName: "Sandeep Kulkarni",
    review:
      "We needed drivers and delivery staff for our business expansion. The platform allowed us to directly connect with manpower providers and get workers efficiently.",
    post: "Transport Company Owner",
  },
];
