import type { MetadataRoute } from "next";
import { getAllBlogs } from "@/lib/blog";

const BASE_URL = "https://www.bookmyworkers.com";

/** Worker skill types */
const workerTypes = ["skilled", "semi-skilled", "unskilled"];

/** 50 worker categories */
const workerCategories = [
  "plumber",
  "electrician",
  "painter",
  "carpenter",
  "mason",
  "tile-fitter",
  "bar-bender",
  "welder",
  "fabricator",
  "steel-fixer",
  "scaffolding-worker",
  "helper",
  "general-labour",
  "construction-worker",
  "factory-worker",
  "machine-operator",
  "loader",
  "unloader",
  "warehouse-worker",
  "packaging-worker",
  "housekeeping-staff",
  "cleaner",
  "domestic-worker",
  "maid",
  "cook",
  "babysitter",
  "caretaker",
  "security-guard",
  "driver",
  "delivery-boy",
  "office-boy",
  "gardener",
  "farm-worker",
  "pest-control-worker",
  "ac-technician",
  "refrigerator-technician",
  "ro-technician",
  "cctv-technician",
  "internet-cable-technician",
  "mobile-repair-technician",
  "computer-technician",
  "data-entry-operator",
  "telecaller",
  "sales-promoter",
  "field-executive",
  "tailor",
  "embroidery-worker",
  "beautician",
  "salon-worker",
  "mechanic",
];

/** 300+ Indian cities */
const cities = [
  "delhi",
  "mumbai",
  "bangalore",
  "hyderabad",
  "chennai",
  "kolkata",
  "pune",
  "ahmedabad",
  "jaipur",
  "surat",
  "lucknow",
  "kanpur",
  "nagpur",
  "indore",
  "thane",
  "bhopal",
  "visakhapatnam",
  "patna",
  "vadodara",
  "ghaziabad",
  "ludhiana",
  "agra",
  "nashik",
  "faridabad",
  "meerut",
  "rajkot",
  "kalyan",
  "vasai-virar",
  "varanasi",
  "srinagar",
  "aurangabad",
  "dhanbad",
  "amritsar",
  "navi-mumbai",
  "allahabad",
  "ranchi",
  "howrah",
  "coimbatore",
  "jabalpur",
  "gwalior",
  "vijayawada",
  "jodhpur",
  "madurai",
  "raipur",
  "kota",
  "guwahati",
  "chandigarh",
  "solapur",
  "hubli",
  "tiruchirappalli",
  "bareilly",
  "moradabad",
  "mysore",
  "gurgaon",
  "aligarh",
  "jalandhar",
  "bhubaneswar",
  "salem",
  "warangal",
  "guntur",
  "bhiwandi",
  "saharanpur",
  "gorakhpur",
  "bikaner",
  "amravati",
  "noida",
  "jamshedpur",
  "bhilai",
  "cuttack",
  "firozabad",
  "kochi",
  "nellore",
  "bhavnagar",
  "dehradun",
  "durgapur",
  "asansol",
  "rourkela",
  "nanded",
  "kolhapur",
  "ajmer",
  "akola",
  "gulbarga",
  "jamnagar",
  "ujjain",
  "loni",
  "siliguri",
  "jhansi",
  "ulhasnagar",
  "jammu",
  "sangli-miraj-kupwad",
  "mangalore",
  "erode",
  "belgaum",
  "ambattur",
  "tirunelveli",
  "malegaon",
  "gaya",
  "jalgaon",
  "udaipur",
  "maheshtala",
  "tiruppur",
  "davanagere",
  "kozhikode",
  "kurnool",
  "rajpur-sonarpur",
  "rajahmundry",
  "bokaro",
  "south-dumdum",
  "bellary",
  "patiala",
  "gopalpur",
  "agartala",
  "bhagalpur",
  "muzaffarnagar",
  "bhatpara",
  "panihati",
  "latur",
  "dhule",
  "rohtak",
  "korba",
  "bhilwara",
  "berhampur",
  "muzaffarpur",
  "ahmednagar",
  "mathura",
  "kollam",
  "avadi",
  "kadapa",
  "kamarhati",
  "sambalpur",
  "bilaspur",
  "shahjahanpur",
  "satara",
  "bijapur",
  "rampur",
  "shivamogga",
  "chandrapur",
  "junagadh",
  "thrissur",
  "alwar",
  "bardhaman",
  "kulti",
  "kakinada",
  "nizamabad",
  "parbhani",
  "tumkur",
  "khammam",
  "ozhukarai",
  "bihar-sharif",
  "panipat",
  "darbhanga",
  "bally",
  "aizawl",
  "dewas",
  "ichalkaranji",
  "tirupati",
  "karnal",
  "bathinda",
  "jalna",
  "eluru",
  "barasat",
  "kirari-suleman-nagar",
  "purnia",
  "satna",
  "mau",
  "sonipat",
  "farrukhabad",
  "sagar",
  "rourkela-industrial-township",
  "durg",
  "imphal",
  "ratlam",
  "hapur",
  "arrah",
  "anantapur",
  "karimnagar",
  "etawah",
  "ambernath",
  "north-dumdum",
  "bharatpur",
  "begusarai",
  "new-delhi",
  "gandhidham",
  "baranagar",
  "tiruvottiyur",
  "pondicherry",
  "sikar",
  "thoothukudi",
  "rewa",
  "mirzapur",
  "raichur",
  "pali",
  "ramagundam",
  "haridwar",
  "vijayanagaram",
  "katihar",
  "nagercoil",
  "sri-ganganagar",
  "karawal-nagar",
  "mango",
  "thane-west",
  "bulandshahr",
  "uluberia",
  "murwara",
  "sambhal",
  "singrauli",
  "nadiad",
  "secunderabad",
  "naihati",
  "yamunanagar",
  "bidhan-nagar",
  "pallavaram",
  "bidar",
  "munger",
  "panchkula",
  "burhanpur",
  "raurkela",
  "kharagpur",
  "dindigul",
  "gandhinagar",
  "hosur",
  "nangloi-jat",
  "english-bazar",
  "ongole",
  "malda",
  "proddatur",
  "haldia",
  "hazaribagh",
  "bhusawal",
  "kharagpur",
  "rewari",
  "mandsaur",
  "bhind",
  "chittoor",
  "midnapore",
  "amroha",
  "anand",
  "morena",
  "bhiwani",
  "berhampore",
  "ambala",
  "morbi",
  "fatehpur",
  "rae-bareli",
  "khora",
  "guna",
  "nagda",
  "lalitpur",
  "datia",
  "siwan",
  "barmer",
  "alappuzha",
  "sultanpur",
  "chhapra",
  "gopalganj",
  "shivpuri",
  "khandwa",
  "hospet",
  "adoni",
  "sambhalpur",
  "tonk",
  "kishanganj",
  "balurghat",
  "gangtok",
  "dimapur",
  "shillong",
  "itanagar",
  "kohima",
  "port-blair",
  "silchar",
  "tezpur",
  "tinsukia",
  "dibrugarh",
  "jorhat",
  "nagaon",
  "goalpara",
  "bongaigaon",
  "karimganj",
  "haldwani",
  "rudrapur",
  "roorkee",
  "almora",
  "pithoragarh",
  "rishikesh",
  "udhampur",
  "anantnag",
  "baramulla",
  "leh",
  "kargil",
  "shimla",
  "solan",
  "mandi",
  "dharamshala",
  "una",
  "palampur",
  "bilaspur-hp",
  "sirsa",
  "hisar",
  "kaithal",
  "kurukshetra",
  "jhajjar",
  "rewari-haryana",
  "palwal",
  "bahadurgarh",
  "mohali",
  "zirakpur",
  "pathankot",
  "moga",
  "hoshiarpur",
  "barnala",
  "phagwara",
  "kapurthala",
  "yamuna-nagar",
  "muzaffarpur-bihar",
  "gaya-bihar",
  "ara",
  "hajipur",
  "motihari",
  "samastipur",
  "sasaram",
  "madhubani",
  "sitamarhi",
  "begusarai-bihar",
  "purnea",
  "darbhanga-bihar",
  "daltonganj",
  "deoghar",
  "giridih",
  "ramgarh",
  "phusro",
  "chakradharpur",
  "bokaro-steel-city",
  "dumka",
  "hazaribag",
  "jagdalpur",
  "rajnandgaon",
  "korba-chhattisgarh",
  "ambikapur",
  "raigarh",
  "dhamtari",
  "mahasamund",
  "bilaspur-chhattisgarh",
  "janjgir",
  "bhilai-nagar",
  "panaji",
  "margao",
  "mapusa",
  "vasco-da-gama",
  "porvorim",
  "verna",
  "bhuj",
  "surendranagar",
  "godhra",
  "bharuch",
  "ankleshwar",
  "valsad",
  "vapi",
  "mehsana",
  "palanpur",
  "porbandar",
  "gandhidham-gujarat",
  "botad",
  "veraval",
  "jetpur",
  "navsari",
  "dahod",
  "ratnagiri",
  "satna-mp",
  "chhindwara",
  "seoni",
  "vidisha",
  "sagar-mp",
  "damoh",
  "khargone",
  "dewas-mp",
  "hoshangabad",
  "itarsi",
  "singrauli-mp",
  "burhanpur-mp",
  "neemuch",
  "mandsaur-mp",
  "ujjain-mp",
  "bhopal-mp",
  "indore-mp",
  "pune-mh",
  "nanded-mh",
  "akola-mh",
  "amravati-mh",
  "solapur-mh",
  "kolhapur-mh",
  "latur-mh",
  "parbhani-mh",
  "beed",
  "osmanabad",
  "wardha",
  "yavatmal",
  "chandrapur-mh",
  "gondia",
  "wardha-mh",
  "sangli",
  "miraj",
  "ichalkaranji-mh",
  "cochin",
  "thrissur-kl",
  "kannur",
  "palakkad",
  "kottayam",
  "kasaragod",
  "malappuram",
  "tirur",
  "manjeri",
  "thalassery",
  "kozhikode-kl",
  "hubballi",
  "mangaluru",
  "belagavi",
  "kalaburagi",
  "ballari",
  "tumakuru",
  "shivamogga-ka",
  "davanagere-ka",
  "bidar-ka",
  "raichur-ka",
  "udupi",
  "chitradurga",
  "hassan",
  "mandya",
  "vijayapura",
  "hosapete",
  "gadag",
  "bagalkot",
  "yadgir",
  "mysuru",
  "warangal-ts",
  "karimnagar-ts",
  "nizamabad-ts",
  "khammam-ts",
  "ramagundam-ts",
  "mahbubnagar",
  "nalgonda",
  "adilabad",
  "suryapet",
  "miryalaguda",
  "siddipet",
  "tirupati-ap",
  "vijayawada-ap",
  "guntur-ap",
  "nellore-ap",
  "kurnool-ap",
  "kadapa-ap",
  "anantapur-ap",
  "eluru-ap",
  "ongole-ap",
  "machilipatnam",
  "tenali",
  "chittoor-ap",
  "srikakulam",
  "vizianagaram",
  "bhimavaram",
  "tanuku",
  "kakinada-ap",
  "rajahmundry-ap",
  "thoothukudi-tn",
  "tiruppur-tn",
  "erode-tn",
  "vellore",
  "thanjavur",
  "nagercoil-tn",
  "hosur-tn",
  "kanchipuram",
  "cuddalore",
  "karur",
  "kumbakonam",
  "sivakasi",
  "tiruvannamalai",
  "pollachi",
  "ooty",
  "tiruchirappalli-tn",
  "madurai-tn",
  "coimbatore-tn",
  "durgapur-wb",
  "asansol-wb",
  "siliguri-wb",
  "malda-wb",
  "baharampur",
  "habra",
  "raiganj",
  "krishnanagar",
  "balurghat-wb",
  "alipurduar",
  "darjeeling",
  "kalimpong",
  "purulia",
  "kharagpur-wb",
  "howrah-wb",
  "bhatpara-wb",
  "cuttack-od",
  "rourkela-od",
  "sambalpur-od",
  "balasore",
  "puri",
  "baripada",
  "jharsuguda",
  "jeypore",
  "bhadrak",
  "paradip",
];

/** Optional: dedupe in case of repeated values */
const uniqueCities = [...new Set(cities)];
const uniqueWorkerCategories = [...new Set(workerCategories)];

export default async function sitemap(): Promise<MetadataRoute.Sitemap> {
  const now = new Date();

  const staticPages: MetadataRoute.Sitemap = [
    {
      url: `${BASE_URL}`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 1,
    },
    {
      url: `${BASE_URL}/about`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
        {
      url: `${BASE_URL}/workers`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
        {
      url: `${BASE_URL}/pricing`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
            {
      url: `${BASE_URL}/hire-workers`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
                {
      url: `${BASE_URL}/workers/manpower-supplier`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
                    {
      url: `${BASE_URL}/workers/labor-supplier`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
                        {
      url: `${BASE_URL}/workers/labor-contractor`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/service`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/category`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.9,
    },
    {
      url: `${BASE_URL}/contact`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.8,
    },
    {
      url: `${BASE_URL}/privacy`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/terms`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/refund`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.3,
    },
    {
      url: `${BASE_URL}/blog`,
      lastModified: now,
      changeFrequency: "daily",
      priority: 0.9,
    },
  ];

  const workerTypePages: MetadataRoute.Sitemap = workerTypes.flatMap((type) =>
    uniqueWorkerCategories.map((category) => ({
      url: `${BASE_URL}/workers/${type}/${category}`,
      lastModified: now,
      changeFrequency: "weekly" as const,
      priority: 0.8,
    }))
  );

  const cityPages: MetadataRoute.Sitemap = uniqueCities.flatMap((city) =>
    uniqueWorkerCategories.map((category) => ({
      url: `${BASE_URL}/workers/${city}/${category}`,
      lastModified: now,
      changeFrequency: "weekly" as const,
      priority: 0.7,
    }))
  );

  let blogPages: MetadataRoute.Sitemap = [];

  try {
    /**
     * Fetch all blogs.
     * Increase limit if needed.
     * Better: create a dedicated API/backend method that returns all blog slugs.
     */
    const blogResponse = await getAllBlogs(1, 5000);

    blogPages = (blogResponse?.blogs || [])
      .filter((blog) => blog?.slug)
      .map((blog) => ({
        url: `${BASE_URL}/blog/${blog.slug}`,
        lastModified: blog.updatedAt
          ? new Date(blog.updatedAt)
          : blog.createdAt
          ? new Date(blog.createdAt)
          : now,
        changeFrequency: "weekly" as const,
        priority: 0.8,
      }));
  } catch (error) {
    console.error("Sitemap blog fetch failed:", error);
    blogPages = [];
  }

  return [...staticPages, ...workerTypePages, ...cityPages, ...blogPages];
}